"""Anomaly / outlier detection pack."""

from __future__ import annotations

from dsai.core.schema import TaskType
from dsai.registry._helpers import MODERATE, OPAQUE, TRANSPARENT, hp, lazy, spec
from dsai.registry.base import Cost, register

AD = [TaskType.ANOMALY_DETECTION]
METRICS = ["n_anomalies", "anomaly_rate", "mean_anomaly_score"]

SPECS = [
    spec(
        key="isolation_forest",
        name="Isolation Forest",
        category="anomaly_detection",
        family="ensemble",
        task_types=AD,
        builder=lazy("sklearn.ensemble:IsolationForest"),
        requires_scaling=False,
        interpretability=MODERATE,
        cost=Cost.LOW,
        nonlinear=True,
        min_rows=50,
        assumptions=["Anomalies are few and easy to separate from the rest"],
        advantages=["Scales to large data", "No scaling needed", "Gives a continuous anomaly score, not just a flag"],
        limitations=["The contamination rate is a guess unless you know it", "Struggles with local anomalies inside dense regions"],
        good_for=["general-purpose outlier detection", "large datasets", "fraud screening"],
        hyperparameters=[
            hp("contamination", "float", 0.05, 0.005, 0.3, description="Expected share of anomalies — this sets the cut-off."),
            hp("n_estimators", "int", 200, 50, 500),
            hp("random_state", "fixed", 42, tune=False),
        ],
        metrics=METRICS,
        tags=["workhorse"],
    ),
    spec(
        key="local_outlier_factor",
        name="Local Outlier Factor",
        category="anomaly_detection",
        family="distance",
        task_types=AD,
        builder=lazy("sklearn.neighbors:LocalOutlierFactor"),
        requires_scaling=True,
        interpretability=MODERATE,
        cost=Cost.MEDIUM,
        nonlinear=True,
        max_recommended_rows=50000,
        assumptions=["Anomalies sit in sparser neighbourhoods than their neighbours", "Scaled features"],
        advantages=["Finds *local* anomalies that global methods miss", "Density ratio explains why a point was flagged"],
        limitations=["No scoring of new data unless novelty mode is enabled", "Sensitive to the neighbour count"],
        good_for=["clustered data with locally unusual points"],
        hyperparameters=[
            hp("n_neighbors", "int", 20, 5, 100),
            hp("contamination", "float", 0.05, 0.005, 0.3),
        ],
        metrics=METRICS,
    ),
    spec(
        key="one_class_svm",
        name="One-Class SVM",
        category="anomaly_detection",
        family="kernel",
        task_types=AD,
        builder=lazy("sklearn.svm:OneClassSVM"),
        requires_scaling=True,
        interpretability=OPAQUE,
        cost=Cost.HIGH,
        nonlinear=True,
        max_recommended_rows=10000,
        assumptions=["Normal data occupies a compact region", "Features scaled"],
        advantages=["Learns a flexible boundary around the normal region"],
        limitations=["Slow", "Very sensitive to nu and gamma", "Nothing to interpret"],
        good_for=["novelty detection on clean training data"],
        hyperparameters=[
            hp("nu", "float", 0.05, 0.005, 0.5, description="Upper bound on the fraction treated as outliers."),
            hp("gamma", "categorical", "scale", choices=["scale", "auto"]),
            hp("kernel", "fixed", "rbf", tune=False),
        ],
        metrics=METRICS,
    ),
    spec(
        key="elliptic_envelope",
        name="Elliptic Envelope (robust covariance)",
        category="anomaly_detection",
        family="statistical",
        task_types=AD,
        builder=lazy("sklearn.covariance:EllipticEnvelope"),
        requires_scaling=True,
        interpretability=MODERATE,
        cost=Cost.MEDIUM,
        max_recommended_rows=20000,
        assumptions=["Normal data is roughly multivariate normal"],
        advantages=["Statistically principled", "Robust covariance resists contamination"],
        limitations=["Fails badly on non-Gaussian or multi-modal data", "Needs more rows than features"],
        good_for=["approximately normal numeric data"],
        hyperparameters=[
            hp("contamination", "float", 0.05, 0.005, 0.3),
            hp("random_state", "fixed", 42, tune=False),
        ],
        metrics=METRICS,
    ),
    spec(
        key="mahalanobis_outlier",
        name="Robust Mahalanobis Distance",
        category="anomaly_detection",
        family="statistical",
        task_types=AD,
        builder=lazy("dsai.registry.adapters:MahalanobisOutlierDetector"),
        module="sklearn",
        requires_scaling=False,
        interpretability=TRANSPARENT,
        cost=Cost.MEDIUM,
        assumptions=["Roughly elliptical numeric data"],
        advantages=["The distance itself is a readable, comparable score", "Accounts for correlation between variables"],
        limitations=["Assumes one elliptical cloud", "Needs more rows than variables"],
        good_for=["multivariate outliers in correlated numeric data"],
        hyperparameters=[hp("contamination", "float", 0.05, 0.005, 0.3)],
        metrics=METRICS,
    ),
    spec(
        key="zscore_outlier",
        name="Z-Score Outlier Detection",
        category="anomaly_detection",
        family="statistical",
        task_types=AD,
        builder=lazy("dsai.registry.adapters:ZScoreOutlierDetector"),
        module="sklearn",
        requires_scaling=False,
        interpretability=TRANSPARENT,
        cost=Cost.VERY_LOW,
        min_rows=20,
        assumptions=["Each variable is roughly normally distributed"],
        advantages=["Trivially explainable: 'this value is 4 standard deviations above the mean'"],
        limitations=["One variable at a time — misses combinations", "The mean and SD are themselves distorted by outliers"],
        good_for=["quick screening", "explaining to non-technical stakeholders"],
        hyperparameters=[hp("threshold", "float", 3.0, 2.0, 5.0, description="Standard deviations from the mean.")],
        metrics=METRICS,
        tags=["univariate", "explainable"],
    ),
    spec(
        key="iqr_outlier",
        name="IQR (Tukey) Outlier Detection",
        category="anomaly_detection",
        family="statistical",
        task_types=AD,
        builder=lazy("dsai.registry.adapters:IQROutlierDetector"),
        module="sklearn",
        requires_scaling=False,
        interpretability=TRANSPARENT,
        cost=Cost.VERY_LOW,
        robust_to_outliers=True,
        min_rows=20,
        assumptions=["None beyond a meaningful ordering"],
        advantages=["Quartiles are not distorted by the outliers themselves", "Matches what a box plot shows"],
        limitations=["Univariate", "Fixed 1.5×IQR rule is a convention, not a law"],
        good_for=["robust screening", "box-plot-based reporting"],
        hyperparameters=[hp("factor", "float", 1.5, 1.0, 3.0, description="1.5 = standard outlier, 3.0 = extreme outlier.")],
        metrics=METRICS,
        tags=["univariate", "explainable", "robust"],
    ),
    spec(
        key="dbscan_outlier",
        name="DBSCAN Noise Detection",
        category="anomaly_detection",
        family="density",
        task_types=AD,
        builder=lazy("dsai.registry.adapters:DBSCANOutlierDetector"),
        module="sklearn",
        requires_scaling=True,
        interpretability=MODERATE,
        cost=Cost.MEDIUM,
        nonlinear=True,
        advantages=["Finds anomalies and clusters in one pass", "No distributional assumptions"],
        limitations=["eps is hard to set", "Everything can end up as noise if eps is too small"],
        good_for=["spatial data", "when clusters and outliers matter together"],
        hyperparameters=[hp("eps", "float", 0.5, 0.1, 3.0), hp("min_samples", "int", 5, 3, 50)],
        metrics=METRICS,
    ),
]

for _spec in SPECS:
    register(_spec, replace=True)

_LOADED = True
