"""Classification algorithm pack."""

from __future__ import annotations

from dsai.core.schema import TaskType
from dsai.registry._helpers import (
    MODERATE, OPAQUE, TRANSPARENT, boosting_params, forest_params, hp, lazy, spec, tree_params,
)
from dsai.registry.base import Cost, register

CLS = [TaskType.BINARY_CLASSIFICATION, TaskType.MULTICLASS_CLASSIFICATION]
BIN = [TaskType.BINARY_CLASSIFICATION]
METRICS = ["accuracy", "balanced_accuracy", "precision", "recall", "f1", "roc_auc", "pr_auc", "mcc", "log_loss"]

SPECS = [
    spec(
        key="logistic_regression",
        name="Logistic Regression",
        category="classification",
        family="linear",
        task_types=CLS,
        builder=lazy("sklearn.linear_model:LogisticRegression"),
        requires_scaling=True,
        supports_coefficients=True,
        supports_predict_proba=True,
        supports_sample_weight=True,
        interpretability=TRANSPARENT,
        cost=Cost.VERY_LOW,
        baseline=True,
        assumptions=[
            "Log-odds of the outcome are a linear function of the predictors",
            "Observations are independent",
            "No severe multicollinearity",
        ],
        advantages=["Coefficients convert directly into odds ratios", "Well-calibrated probabilities", "Fast"],
        limitations=["Misses interactions and curves unless you add them", "Needs scaling for regularisation to be fair"],
        good_for=["explanatory analysis", "baseline", "risk scoring", "regulated environments"],
        hyperparameters=[
            hp("C", "float", 1.0, 0.001, 100.0, log=True, description="Inverse regularisation; smaller = stronger penalty."),
            hp("penalty", "categorical", "l2", choices=["l2", "l1", None]),
            hp("class_weight", "categorical", None, choices=[None, "balanced"],
               description="'balanced' compensates for rare classes."),
            hp("solver", "fixed", "liblinear", tune=False),
            hp("max_iter", "fixed", 2000, tune=False),
            hp("random_state", "fixed", 42, tune=False),
        ],
        metrics=METRICS,
        tags=["baseline", "explanatory", "calibrated"],
    ),
    spec(
        key="logistic_regression_multinomial",
        name="Multinomial Logistic Regression",
        category="classification",
        family="linear",
        task_types=[TaskType.MULTICLASS_CLASSIFICATION],
        builder=lazy("sklearn.linear_model:LogisticRegression"),
        requires_scaling=True,
        supports_coefficients=True,
        supports_predict_proba=True,
        interpretability=TRANSPARENT,
        cost=Cost.LOW,
        assumptions=["Linear log-odds for each class against the reference"],
        advantages=["Models all classes jointly instead of one-vs-rest", "Coherent probabilities across classes"],
        limitations=["Still a linear decision boundary"],
        good_for=["multi-class explanatory analysis"],
        hyperparameters=[
            hp("C", "float", 1.0, 0.001, 100.0, log=True),
            hp("solver", "fixed", "lbfgs", tune=False),
            hp("max_iter", "fixed", 2000, tune=False),
            hp("random_state", "fixed", 42, tune=False),
        ],
        metrics=METRICS,
    ),
    spec(
        key="ridge_classifier",
        name="Ridge Classifier",
        category="classification",
        family="linear",
        task_types=CLS,
        builder=lazy("sklearn.linear_model:RidgeClassifier"),
        requires_scaling=True,
        supports_coefficients=True,
        interpretability=TRANSPARENT,
        cost=Cost.VERY_LOW,
        handles_high_dimensionality=True,
        advantages=["Very fast", "Stable with correlated predictors"],
        limitations=["No probability output", "Linear boundary only"],
        good_for=["wide data", "fast screening"],
        hyperparameters=[hp("alpha", "float", 1.0, 0.001, 100.0, log=True),
                         hp("class_weight", "categorical", None, choices=[None, "balanced"])],
        metrics=["accuracy", "balanced_accuracy", "f1", "mcc"],
    ),
    spec(
        key="sgd_classifier",
        name="SGD Classifier (linear, online)",
        category="classification",
        family="linear",
        task_types=CLS,
        builder=lazy("sklearn.linear_model:SGDClassifier"),
        requires_scaling=True,
        supports_coefficients=True,
        interpretability=MODERATE,
        cost=Cost.VERY_LOW,
        handles_high_dimensionality=True,
        advantages=["Scales to very large datasets", "Supports several loss functions"],
        limitations=["Sensitive to learning rate and scaling", "Noisier than batch solvers"],
        good_for=["very large datasets", "text features"],
        hyperparameters=[
            hp("loss", "categorical", "log_loss", choices=["log_loss", "hinge", "modified_huber"]),
            hp("alpha", "float", 0.0001, 1e-6, 0.1, log=True),
            hp("max_iter", "fixed", 2000, tune=False),
            hp("random_state", "fixed", 42, tune=False),
        ],
        metrics=METRICS,
    ),
    spec(
        key="gaussian_nb",
        name="Gaussian Naive Bayes",
        category="classification",
        family="probabilistic",
        task_types=CLS,
        builder=lazy("sklearn.naive_bayes:GaussianNB"),
        requires_scaling=False,
        supports_predict_proba=True,
        interpretability=MODERATE,
        cost=Cost.VERY_LOW,
        min_rows=20,
        assumptions=["Features are conditionally independent given the class", "Each feature is roughly normal within a class"],
        advantages=["Trains in one pass", "Works with very little data", "Surprisingly hard to beat on some problems"],
        limitations=["The independence assumption is usually false", "Probabilities are poorly calibrated"],
        good_for=["tiny datasets", "quick baselines"],
        hyperparameters=[hp("var_smoothing", "float", 1e-9, 1e-12, 1e-3, log=True)],
        metrics=METRICS,
        tags=["baseline", "fast"],
    ),
    spec(
        key="bernoulli_nb",
        name="Bernoulli Naive Bayes",
        category="classification",
        family="probabilistic",
        task_types=CLS,
        builder=lazy("sklearn.naive_bayes:BernoulliNB"),
        requires_scaling=False,
        supports_predict_proba=True,
        interpretability=MODERATE,
        cost=Cost.VERY_LOW,
        assumptions=["Features are binary (or are binarised)"],
        advantages=["Ideal for presence/absence indicators"],
        limitations=["Throws away magnitude information"],
        good_for=["binary indicator features", "text presence data"],
        hyperparameters=[hp("alpha", "float", 1.0, 0.01, 10.0, log=True, description="Laplace smoothing.")],
        metrics=METRICS,
    ),
    spec(
        key="multinomial_nb",
        name="Multinomial Naive Bayes",
        category="classification",
        family="probabilistic",
        task_types=CLS,
        builder=lazy("sklearn.naive_bayes:MultinomialNB"),
        requires_scaling=False,
        supports_predict_proba=True,
        interpretability=MODERATE,
        cost=Cost.VERY_LOW,
        assumptions=["Features are non-negative counts or frequencies"],
        advantages=["The standard baseline for bag-of-words text"],
        limitations=["Fails on negative values — needs count or TF-IDF style input"],
        good_for=["text classification", "count features"],
        hyperparameters=[hp("alpha", "float", 1.0, 0.01, 10.0, log=True)],
        metrics=METRICS,
        tags=["text"],
    ),
    spec(
        key="lda",
        name="Linear Discriminant Analysis",
        category="classification",
        family="statistical",
        task_types=CLS,
        builder=lazy("sklearn.discriminant_analysis:LinearDiscriminantAnalysis"),
        requires_scaling=True,
        supports_coefficients=True,
        supports_predict_proba=True,
        interpretability=TRANSPARENT,
        cost=Cost.VERY_LOW,
        assumptions=["Classes are normally distributed", "All classes share one covariance matrix"],
        advantages=["Works well on small samples", "Doubles as a supervised dimensionality reducer"],
        limitations=["Breaks when class covariances differ", "Linear boundary"],
        good_for=["small datasets", "supervised projection"],
        hyperparameters=[hp("solver", "categorical", "svd", choices=["svd", "lsqr", "eigen"])],
        metrics=METRICS,
    ),
    spec(
        key="qda",
        name="Quadratic Discriminant Analysis",
        category="classification",
        family="statistical",
        task_types=CLS,
        builder=lazy("sklearn.discriminant_analysis:QuadraticDiscriminantAnalysis"),
        requires_scaling=True,
        supports_predict_proba=True,
        interpretability=MODERATE,
        cost=Cost.LOW,
        nonlinear=True,
        assumptions=["Classes are normally distributed with their own covariance matrices"],
        advantages=["Curved decision boundaries without leaving the statistical framework"],
        limitations=["Needs plenty of rows per class", "Unstable with many features"],
        good_for=["classes with different spread"],
        hyperparameters=[hp("reg_param", "float", 0.0, 0.0, 1.0, description="Shrinks covariance towards the pooled estimate.")],
        metrics=METRICS,
    ),
    spec(
        key="knn_classifier",
        name="K-Nearest Neighbours Classifier",
        category="classification",
        family="distance",
        task_types=CLS,
        builder=lazy("sklearn.neighbors:KNeighborsClassifier"),
        requires_scaling=True,
        supports_predict_proba=True,
        interpretability=MODERATE,
        cost=Cost.LOW,
        nonlinear=True,
        max_recommended_features=50,
        assumptions=["Nearby rows share a class", "Features are scaled so distance is meaningful"],
        advantages=["No training step", "A prediction can be justified by showing its neighbours"],
        limitations=["Suffers in high dimensions", "Slow at prediction time on large data"],
        good_for=["local decision boundaries", "small feature sets"],
        hyperparameters=[
            hp("n_neighbors", "int", 5, 1, 50),
            hp("weights", "categorical", "uniform", choices=["uniform", "distance"]),
            hp("p", "categorical", 2, choices=[1, 2]),
        ],
        metrics=METRICS,
    ),
    spec(
        key="decision_tree_classifier",
        name="Decision Tree Classifier",
        category="classification",
        family="tree",
        task_types=CLS,
        builder=lazy("sklearn.tree:DecisionTreeClassifier"),
        requires_scaling=False,
        supports_feature_importance=True,
        supports_predict_proba=True,
        supports_sample_weight=True,
        interpretability=TRANSPARENT,
        cost=Cost.LOW,
        nonlinear=True,
        robust_to_outliers=True,
        assumptions=["None"],
        advantages=["Readable as a set of business rules", "Handles mixed data with no scaling"],
        limitations=["A single tree is unstable", "Overfits quickly without depth limits"],
        good_for=["rule extraction", "stakeholder explanation"],
        hyperparameters=tree_params(5) + [
            hp("criterion", "categorical", "gini", choices=["gini", "entropy"]),
            hp("class_weight", "categorical", None, choices=[None, "balanced"]),
            hp("random_state", "fixed", 42, tune=False),
        ],
        metrics=METRICS,
        tags=["rules"],
    ),
    spec(
        key="random_forest_classifier",
        name="Random Forest Classifier",
        category="classification",
        family="ensemble",
        task_types=CLS,
        builder=lazy("sklearn.ensemble:RandomForestClassifier"),
        requires_scaling=False,
        supports_feature_importance=True,
        supports_predict_proba=True,
        supports_sample_weight=True,
        interpretability=MODERATE,
        cost=Cost.MEDIUM,
        nonlinear=True,
        robust_to_outliers=True,
        advantages=["Strong default performance", "Captures interactions", "Handles imbalance with class weights"],
        limitations=["Larger and slower than linear models", "Importances are biased towards high-cardinality features"],
        good_for=["general-purpose classification", "mixed data types"],
        hyperparameters=forest_params() + [hp("class_weight", "categorical", None, choices=[None, "balanced", "balanced_subsample"])],
        metrics=METRICS,
        tags=["workhorse"],
    ),
    spec(
        key="extra_trees_classifier",
        name="Extra Trees Classifier",
        category="classification",
        family="ensemble",
        task_types=CLS,
        builder=lazy("sklearn.ensemble:ExtraTreesClassifier"),
        requires_scaling=False,
        supports_feature_importance=True,
        supports_predict_proba=True,
        interpretability=MODERATE,
        cost=Cost.MEDIUM,
        nonlinear=True,
        advantages=["Faster than Random Forest with similar accuracy"],
        limitations=["Slightly higher bias", "Same importance biases"],
        good_for=["noisy data"],
        hyperparameters=forest_params(),
        metrics=METRICS,
    ),
    spec(
        key="gradient_boosting_classifier",
        name="Gradient Boosting Classifier",
        category="classification",
        family="ensemble",
        task_types=CLS,
        builder=lazy("sklearn.ensemble:GradientBoostingClassifier"),
        requires_scaling=False,
        supports_feature_importance=True,
        supports_predict_proba=True,
        interpretability=MODERATE,
        cost=Cost.HIGH,
        nonlinear=True,
        advantages=["Typically the highest accuracy on tabular data"],
        limitations=["Slow to train", "Overfits without tuning"],
        good_for=["maximum accuracy"],
        hyperparameters=boosting_params(),
        metrics=METRICS,
        tags=["high_accuracy"],
    ),
    spec(
        key="hist_gradient_boosting_classifier",
        name="Histogram Gradient Boosting Classifier",
        category="classification",
        family="ensemble",
        task_types=CLS,
        builder=lazy("sklearn.ensemble:HistGradientBoostingClassifier"),
        requires_scaling=False,
        handles_missing=True,
        supports_predict_proba=True,
        interpretability=MODERATE,
        cost=Cost.MEDIUM,
        nonlinear=True,
        advantages=["Native missing-value support", "Fast on large datasets"],
        limitations=["No built-in importances"],
        good_for=["large data", "missing values"],
        hyperparameters=[
            hp("max_iter", "int", 300, 50, 1000),
            hp("learning_rate", "float", 0.1, 0.01, 0.3, log=True),
            hp("max_depth", "int", None, 2, 15),
            hp("l2_regularization", "float", 0.0, 0.0, 10.0),
            hp("random_state", "fixed", 42, tune=False),
        ],
        metrics=METRICS,
        tags=["fast", "missing_tolerant"],
    ),
    spec(
        key="adaboost_classifier",
        name="AdaBoost Classifier",
        category="classification",
        family="ensemble",
        task_types=CLS,
        builder=lazy("sklearn.ensemble:AdaBoostClassifier"),
        requires_scaling=False,
        supports_feature_importance=True,
        supports_predict_proba=True,
        interpretability=MODERATE,
        cost=Cost.MEDIUM,
        nonlinear=True,
        advantages=["Few hyper-parameters", "Focuses effort on the hard cases"],
        limitations=["Very sensitive to label noise and outliers"],
        good_for=["clean moderate-size data"],
        hyperparameters=[
            hp("n_estimators", "int", 200, 50, 800),
            hp("learning_rate", "float", 1.0, 0.01, 2.0, log=True),
            hp("random_state", "fixed", 42, tune=False),
        ],
        metrics=METRICS,
    ),
    spec(
        key="bagging_classifier",
        name="Bagging Classifier",
        category="classification",
        family="ensemble",
        task_types=CLS,
        builder=lazy("sklearn.ensemble:BaggingClassifier"),
        requires_scaling=False,
        supports_predict_proba=True,
        interpretability=OPAQUE,
        cost=Cost.MEDIUM,
        nonlinear=True,
        advantages=["Reduces variance of any unstable base learner"],
        limitations=["No bias reduction", "Opaque"],
        good_for=["stabilising noisy models"],
        hyperparameters=[hp("n_estimators", "int", 50, 10, 300), hp("random_state", "fixed", 42, tune=False)],
        metrics=METRICS,
    ),
    spec(
        key="xgboost_classifier",
        name="XGBoost Classifier",
        category="classification",
        family="ensemble",
        task_types=CLS,
        builder=lazy("xgboost:XGBClassifier"),
        module="xgboost",
        requires_scaling=False,
        handles_missing=True,
        supports_feature_importance=True,
        supports_predict_proba=True,
        supports_sample_weight=True,
        interpretability=MODERATE,
        cost=Cost.MEDIUM,
        nonlinear=True,
        advantages=["Excellent accuracy", "Handles missing values", "scale_pos_weight handles imbalance directly"],
        limitations=["Many hyper-parameters", "Extra dependency"],
        good_for=["maximum accuracy", "imbalanced classification"],
        hyperparameters=boosting_params() + [
            hp("reg_lambda", "float", 1.0, 0.0, 10.0),
            hp("colsample_bytree", "float", 1.0, 0.4, 1.0),
            hp("n_jobs", "fixed", -1, tune=False),
        ],
        metrics=METRICS,
        tags=["high_accuracy", "missing_tolerant"],
    ),
    spec(
        key="lightgbm_classifier",
        name="LightGBM Classifier",
        category="classification",
        family="ensemble",
        task_types=CLS,
        builder=lazy("lightgbm:LGBMClassifier"),
        module="lightgbm",
        requires_scaling=False,
        handles_missing=True,
        handles_categorical=True,
        supports_feature_importance=True,
        supports_predict_proba=True,
        interpretability=MODERATE,
        cost=Cost.LOW,
        nonlinear=True,
        min_rows=100,
        advantages=["Very fast", "Native categorical support", "class_weight for imbalance"],
        limitations=["Overfits small datasets", "Extra dependency"],
        good_for=["large data", "categorical-heavy data"],
        hyperparameters=[
            hp("n_estimators", "int", 300, 50, 1500),
            hp("learning_rate", "float", 0.05, 0.01, 0.3, log=True),
            hp("num_leaves", "int", 31, 8, 255),
            hp("min_child_samples", "int", 20, 5, 100),
            hp("class_weight", "categorical", None, choices=[None, "balanced"]),
            hp("random_state", "fixed", 42, tune=False),
            hp("verbose", "fixed", -1, tune=False),
            hp("n_jobs", "fixed", -1, tune=False),
        ],
        metrics=METRICS,
        tags=["fast", "high_accuracy"],
    ),
    spec(
        key="catboost_classifier",
        name="CatBoost Classifier",
        category="classification",
        family="ensemble",
        task_types=CLS,
        builder=lazy("catboost:CatBoostClassifier"),
        module="catboost",
        requires_scaling=False,
        handles_missing=True,
        handles_categorical=True,
        supports_feature_importance=True,
        supports_predict_proba=True,
        interpretability=MODERATE,
        cost=Cost.HIGH,
        nonlinear=True,
        advantages=["Best categorical handling", "Strong defaults"],
        limitations=["Slow", "Heavy dependency"],
        good_for=["categorical-heavy data"],
        hyperparameters=[
            hp("iterations", "int", 500, 100, 2000),
            hp("learning_rate", "float", 0.05, 0.01, 0.3, log=True),
            hp("depth", "int", 6, 3, 10),
            hp("verbose", "fixed", 0, tune=False),
            hp("random_seed", "fixed", 42, tune=False),
        ],
        metrics=METRICS,
    ),
    spec(
        key="svc_rbf",
        name="Support Vector Machine (RBF kernel)",
        category="classification",
        family="kernel",
        task_types=CLS,
        builder=lazy("sklearn.svm:SVC"),
        requires_scaling=True,
        supports_predict_proba=True,
        interpretability=OPAQUE,
        cost=Cost.HIGH,
        nonlinear=True,
        max_recommended_rows=20000,
        assumptions=["Features scaled to a comparable range"],
        advantages=["Strong on small, clean, nonlinear problems", "Margin maximisation generalises well"],
        limitations=["Scales poorly", "Probabilities need an extra calibration fit", "Opaque"],
        good_for=["small nonlinear problems"],
        hyperparameters=[
            hp("C", "float", 1.0, 0.01, 100.0, log=True),
            hp("gamma", "categorical", "scale", choices=["scale", "auto", 0.01, 0.1]),
            hp("class_weight", "categorical", None, choices=[None, "balanced"]),
            hp("kernel", "fixed", "rbf", tune=False),
            hp("probability", "fixed", True, tune=False),
            hp("random_state", "fixed", 42, tune=False),
        ],
        metrics=METRICS,
    ),
    spec(
        key="svc_linear",
        name="Linear Support Vector Machine",
        category="classification",
        family="kernel",
        task_types=CLS,
        builder=lazy("sklearn.svm:LinearSVC"),
        requires_scaling=True,
        supports_coefficients=True,
        interpretability=MODERATE,
        cost=Cost.LOW,
        handles_high_dimensionality=True,
        advantages=["Fast on wide data", "Strong text baseline"],
        limitations=["No probabilities", "Linear boundary only"],
        good_for=["text classification", "wide data"],
        hyperparameters=[
            hp("C", "float", 1.0, 0.01, 100.0, log=True),
            hp("class_weight", "categorical", None, choices=[None, "balanced"]),
            hp("max_iter", "fixed", 5000, tune=False),
            hp("random_state", "fixed", 42, tune=False),
        ],
        metrics=["accuracy", "balanced_accuracy", "precision", "recall", "f1", "mcc"],
    ),
    spec(
        key="svc_poly",
        name="Polynomial Kernel SVM",
        category="classification",
        family="kernel",
        task_types=CLS,
        builder=lazy("sklearn.svm:SVC"),
        requires_scaling=True,
        supports_predict_proba=True,
        interpretability=OPAQUE,
        cost=Cost.HIGH,
        nonlinear=True,
        max_recommended_rows=10000,
        advantages=["Captures polynomial interaction structure explicitly"],
        limitations=["Slow and numerically fragile at high degrees"],
        good_for=["interaction-driven problems"],
        hyperparameters=[
            hp("C", "float", 1.0, 0.01, 100.0, log=True),
            hp("degree", "int", 3, 2, 5),
            hp("kernel", "fixed", "poly", tune=False),
            hp("probability", "fixed", True, tune=False),
            hp("random_state", "fixed", 42, tune=False),
        ],
        metrics=METRICS,
    ),
    spec(
        key="mlp_classifier",
        name="Neural Network Classifier (MLP)",
        category="classification",
        family="neural",
        task_types=CLS,
        builder=lazy("sklearn.neural_network:MLPClassifier"),
        requires_scaling=True,
        supports_predict_proba=True,
        interpretability=OPAQUE,
        cost=Cost.HIGH,
        nonlinear=True,
        min_rows=200,
        assumptions=["Scaled inputs", "Enough rows for the number of weights"],
        advantages=["Learns complex boundaries given enough data"],
        limitations=["Data hungry", "Opaque", "Sensitive to scaling and initialisation"],
        good_for=["large datasets"],
        hyperparameters=[
            hp("hidden_layer_sizes", "categorical", (64, 32), choices=[(32,), (64, 32), (128, 64), (100,)]),
            hp("alpha", "float", 0.0001, 1e-6, 1.0, log=True),
            hp("learning_rate_init", "float", 0.001, 1e-4, 0.05, log=True),
            hp("max_iter", "fixed", 800, tune=False),
            hp("early_stopping", "fixed", True, tune=False),
            hp("random_state", "fixed", 42, tune=False),
        ],
        metrics=METRICS,
    ),
    spec(
        key="gaussian_process_classifier",
        name="Gaussian Process Classifier",
        category="classification",
        family="probabilistic",
        task_types=CLS,
        builder=lazy("sklearn.gaussian_process:GaussianProcessClassifier"),
        requires_scaling=True,
        supports_predict_proba=True,
        interpretability=OPAQUE,
        cost=Cost.VERY_HIGH,
        nonlinear=True,
        max_recommended_rows=2000,
        advantages=["Well-calibrated uncertainty on small data"],
        limitations=["Cubic scaling makes it impractical beyond a couple of thousand rows"],
        good_for=["very small datasets where uncertainty matters"],
        hyperparameters=[hp("random_state", "fixed", 42, tune=False)],
        metrics=METRICS,
        tags=["uncertainty"],
    ),
    spec(
        key="stacking_classifier",
        name="Stacking Ensemble Classifier",
        category="classification",
        family="ensemble",
        task_types=CLS,
        builder=lazy("dsai.registry.adapters:DefaultStackingClassifier"),
        requires_scaling=True,
        supports_predict_proba=True,
        interpretability=OPAQUE,
        cost=Cost.VERY_HIGH,
        nonlinear=True,
        min_rows=200,
        advantages=["Learns how to weight complementary models"],
        limitations=["Expensive", "Meta-learner can overfit", "Very hard to explain"],
        good_for=["last few points of accuracy"],
        hyperparameters=[hp("cv", "int", 5, 3, 10, tune=False)],
        metrics=METRICS,
    ),
    spec(
        key="voting_classifier",
        name="Voting Ensemble Classifier",
        category="classification",
        family="ensemble",
        task_types=CLS,
        builder=lazy("dsai.registry.adapters:DefaultVotingClassifier"),
        requires_scaling=True,
        supports_predict_proba=True,
        interpretability=OPAQUE,
        cost=Cost.HIGH,
        nonlinear=True,
        min_rows=100,
        advantages=["Averages away individual model quirks"],
        limitations=["Slow", "Rarely beats a tuned booster"],
        good_for=["stability"],
        hyperparameters=[hp("voting", "categorical", "soft", choices=["soft", "hard"])],
        metrics=METRICS,
    ),
    spec(
        key="dummy_classifier",
        name="Baseline (predict the majority class)",
        category="classification",
        family="baseline",
        task_types=CLS,
        builder=lazy("sklearn.dummy:DummyClassifier"),
        requires_scaling=False,
        supports_predict_proba=True,
        interpretability=TRANSPARENT,
        cost=Cost.VERY_LOW,
        baseline=True,
        min_rows=5,
        advantages=["Exposes how much of the 'accuracy' is just class imbalance"],
        limitations=["Learns nothing — deliberately"],
        good_for=["sanity check on imbalanced data"],
        hyperparameters=[hp("strategy", "categorical", "most_frequent", choices=["most_frequent", "stratified", "prior"])],
        metrics=METRICS,
        tags=["baseline"],
    ),
]

for _spec in SPECS:
    register(_spec, replace=True)

_LOADED = True
