"""Clustering algorithm pack."""

from __future__ import annotations

from dsai.core.schema import TaskType
from dsai.registry._helpers import MODERATE, OPAQUE, TRANSPARENT, hp, lazy, spec
from dsai.registry.base import Cost, register

CLU = [TaskType.CLUSTERING]
METRICS = ["silhouette", "calinski_harabasz", "davies_bouldin"]

SPECS = [
    spec(
        key="kmeans",
        name="K-Means",
        category="clustering",
        family="centroid",
        task_types=CLU,
        builder=lazy("sklearn.cluster:KMeans"),
        requires_scaling=True,
        interpretability=TRANSPARENT,
        cost=Cost.LOW,
        assumptions=[
            "Clusters are roughly spherical and similar in size",
            "Euclidean distance is meaningful, so features must be scaled",
            "The number of clusters is chosen in advance",
        ],
        advantages=["Fast and scalable", "Centroids describe each segment directly", "The default everyone understands"],
        limitations=["Forces every point into a cluster", "Struggles with elongated or unequal clusters", "Outliers drag centroids"],
        good_for=["customer segmentation", "large datasets", "a first look at structure"],
        hyperparameters=[
            hp("n_clusters", "int", 3, 2, 15, description="Number of segments to create."),
            hp("n_init", "fixed", 10, tune=False),
            hp("random_state", "fixed", 42, tune=False),
        ],
        metrics=METRICS,
        tags=["workhorse", "segmentation"],
    ),
    spec(
        key="minibatch_kmeans",
        name="Mini-Batch K-Means",
        category="clustering",
        family="centroid",
        task_types=CLU,
        builder=lazy("sklearn.cluster:MiniBatchKMeans"),
        requires_scaling=True,
        interpretability=TRANSPARENT,
        cost=Cost.VERY_LOW,
        advantages=["Handles millions of rows", "Near K-Means quality at a fraction of the time"],
        limitations=["Slightly worse solutions than full K-Means", "Results vary a little between runs"],
        good_for=["very large datasets"],
        hyperparameters=[
            hp("n_clusters", "int", 3, 2, 20),
            hp("batch_size", "int", 1024, 256, 8192, tune=False),
            hp("random_state", "fixed", 42, tune=False),
        ],
        metrics=METRICS,
        min_rows=500,
    ),
    spec(
        key="kmedoids",
        name="K-Medoids (PAM)",
        category="clustering",
        family="centroid",
        task_types=CLU,
        builder=lazy("dsai.registry.adapters:KMedoids"),
        module="sklearn",
        requires_scaling=True,
        interpretability=TRANSPARENT,
        cost=Cost.MEDIUM,
        robust_to_outliers=True,
        max_recommended_rows=10000,
        assumptions=["A distance metric that makes sense for the data"],
        advantages=["Each centre is a real observation you can point at", "Far less outlier-sensitive than K-Means"],
        limitations=["O(n²) distance matrix limits dataset size"],
        good_for=["outlier-heavy data", "explaining segments by example"],
        hyperparameters=[
            hp("n_clusters", "int", 3, 2, 15),
            hp("metric", "categorical", "euclidean", choices=["euclidean", "manhattan", "cosine"]),
            hp("random_state", "fixed", 42, tune=False),
        ],
        metrics=METRICS,
    ),
    spec(
        key="agglomerative",
        name="Agglomerative (Hierarchical) Clustering",
        category="clustering",
        family="hierarchical",
        task_types=CLU,
        builder=lazy("sklearn.cluster:AgglomerativeClustering"),
        requires_scaling=True,
        interpretability=MODERATE,
        cost=Cost.MEDIUM,
        max_recommended_rows=20000,
        assumptions=["A meaningful distance and linkage choice"],
        advantages=["Produces a dendrogram showing the full merge history", "No assumption of spherical clusters with Ward linkage"],
        limitations=["O(n²) memory", "Merges are final — no reassignment", "No native way to assign new rows"],
        good_for=["exploring nested structure", "small to medium datasets"],
        hyperparameters=[
            hp("n_clusters", "int", 3, 2, 15),
            hp("linkage", "categorical", "ward", choices=["ward", "complete", "average", "single"],
               description="Ward minimises within-cluster variance; average/complete suit non-spherical shapes."),
        ],
        metrics=METRICS,
        tags=["dendrogram"],
    ),
    spec(
        key="birch",
        name="BIRCH",
        category="clustering",
        family="hierarchical",
        task_types=CLU,
        builder=lazy("sklearn.cluster:Birch"),
        requires_scaling=True,
        interpretability=MODERATE,
        cost=Cost.LOW,
        advantages=["Streams through large data in one pass", "Low memory footprint"],
        limitations=["Only handles numeric features", "Sensitive to the threshold parameter"],
        good_for=["very large datasets", "streaming"],
        hyperparameters=[
            hp("n_clusters", "int", 3, 2, 15),
            hp("threshold", "float", 0.5, 0.1, 2.0, description="Radius below which points merge into a sub-cluster."),
        ],
        metrics=METRICS,
        min_rows=200,
    ),
    spec(
        key="dbscan",
        name="DBSCAN",
        category="clustering",
        family="density",
        task_types=CLU,
        builder=lazy("sklearn.cluster:DBSCAN"),
        requires_scaling=True,
        interpretability=MODERATE,
        cost=Cost.MEDIUM,
        robust_to_outliers=True,
        assumptions=["Clusters are dense regions separated by sparser ones", "One density level suits every cluster"],
        advantages=["Finds arbitrary shapes", "Decides the number of clusters itself", "Labels genuine noise as noise"],
        limitations=["eps is hard to choose", "Fails when clusters have very different densities", "Degrades in high dimensions"],
        good_for=["irregular shapes", "data with noise", "spatial data"],
        hyperparameters=[
            hp("eps", "float", 0.5, 0.1, 3.0, description="Neighbourhood radius — the parameter that matters most."),
            hp("min_samples", "int", 5, 3, 50, description="Points needed in a neighbourhood to form a dense core."),
        ],
        metrics=METRICS,
        tags=["density", "noise_aware"],
    ),
    spec(
        key="hdbscan",
        name="HDBSCAN",
        category="clustering",
        family="density",
        task_types=CLU,
        builder=lazy("sklearn.cluster:HDBSCAN"),
        requires_scaling=True,
        interpretability=MODERATE,
        cost=Cost.MEDIUM,
        robust_to_outliers=True,
        assumptions=["Clusters are dense regions, possibly at different densities"],
        advantages=["No eps to guess", "Handles varying densities", "Gives per-point cluster membership strength"],
        limitations=["Slower than DBSCAN", "Can label a lot of points as noise"],
        good_for=["varying-density clusters", "exploratory segmentation"],
        hyperparameters=[
            hp("min_cluster_size", "int", 15, 5, 100, description="Smallest group size worth calling a cluster."),
            hp("min_samples", "int", None, 1, 50),
        ],
        metrics=METRICS,
        min_rows=100,
        tags=["density", "noise_aware"],
    ),
    spec(
        key="optics",
        name="OPTICS",
        category="clustering",
        family="density",
        task_types=CLU,
        builder=lazy("sklearn.cluster:OPTICS"),
        requires_scaling=True,
        interpretability=MODERATE,
        cost=Cost.HIGH,
        robust_to_outliers=True,
        max_recommended_rows=10000,
        advantages=["Reveals cluster structure across a range of densities via the reachability plot"],
        limitations=["Slow", "Output needs interpretation rather than reading off labels"],
        good_for=["density structure exploration"],
        hyperparameters=[
            hp("min_samples", "int", 5, 3, 50),
            hp("xi", "float", 0.05, 0.01, 0.3, description="Steepness threshold for extracting clusters."),
        ],
        metrics=METRICS,
    ),
    spec(
        key="mean_shift",
        name="Mean Shift",
        category="clustering",
        family="density",
        task_types=CLU,
        builder=lazy("sklearn.cluster:MeanShift"),
        requires_scaling=True,
        interpretability=MODERATE,
        cost=Cost.VERY_HIGH,
        max_recommended_rows=5000,
        advantages=["Discovers the number of clusters from the data", "Finds modes of the density"],
        limitations=["Very slow", "Bandwidth choice dominates the result"],
        good_for=["mode finding", "image segmentation style problems"],
        hyperparameters=[hp("bandwidth", "float", None, 0.1, 5.0), hp("bin_seeding", "bool", True, tune=False)],
        metrics=METRICS,
    ),
    spec(
        key="gaussian_mixture",
        name="Gaussian Mixture Model",
        category="clustering",
        family="probabilistic",
        task_types=CLU,
        builder=lazy("sklearn.mixture:GaussianMixture"),
        requires_scaling=True,
        interpretability=MODERATE,
        cost=Cost.MEDIUM,
        assumptions=["Data is a mixture of Gaussian components"],
        advantages=["Soft memberships — a row can partly belong to two segments", "Elliptical clusters, not just spheres", "AIC/BIC give a principled way to choose k"],
        limitations=["Assumes normality", "Can converge to a poor local optimum", "Needs more rows than K-Means"],
        good_for=["overlapping segments", "probabilistic assignment"],
        hyperparameters=[
            hp("n_components", "int", 3, 2, 15, description="Number of mixture components."),
            hp("covariance_type", "categorical", "full", choices=["full", "tied", "diag", "spherical"]),
            hp("random_state", "fixed", 42, tune=False),
        ],
        metrics=METRICS + ["aic", "bic"],
        min_rows=100,
        tags=["soft_clustering"],
    ),
    spec(
        key="bayesian_gaussian_mixture",
        name="Bayesian Gaussian Mixture",
        category="clustering",
        family="probabilistic",
        task_types=CLU,
        builder=lazy("sklearn.mixture:BayesianGaussianMixture"),
        requires_scaling=True,
        interpretability=MODERATE,
        cost=Cost.HIGH,
        advantages=["Prunes unnecessary components automatically, so k is less critical"],
        limitations=["Slower", "Sensitive to the prior settings"],
        good_for=["unknown number of clusters"],
        hyperparameters=[
            hp("n_components", "int", 10, 2, 20, description="Upper bound on clusters; unused ones shrink away."),
            hp("covariance_type", "categorical", "full", choices=["full", "diag"]),
            hp("random_state", "fixed", 42, tune=False),
        ],
        metrics=METRICS,
        min_rows=200,
        tags=["soft_clustering"],
    ),
    spec(
        key="latent_class_analysis",
        name="Latent Class Analysis",
        category="clustering",
        family="probabilistic",
        task_types=CLU,
        builder=lazy("dsai.registry.adapters:LatentClassAnalysis"),
        module="sklearn",
        requires_scaling=False,
        interpretability=MODERATE,
        cost=Cost.MEDIUM,
        assumptions=[
            "Indicators are binary or categorical, not continuous measurements",
            "Items are independent of each other once class membership is known "
            "(local independence) — the classes are what explain any correlation between them",
        ],
        advantages=[
            "Each class is read directly as a set of item probabilities, not a distance",
            "Soft membership — a row's probability of belonging to each class, not a hard assignment",
            "AIC/BIC give a principled way to choose the number of classes",
        ],
        limitations=[
            "A continuous column is median-split into two levels before fitting — a real "
            "technique, but a modelling choice made for you, not a neutral default",
            "Assumes local independence; strongly correlated items within a class inflate "
            "that class's apparent size",
            "Can converge to a poor local optimum — more restarts (n_init) trade time for reliability",
        ],
        good_for=["survey or yes/no style indicators", "segments defined by response patterns, not distance"],
        hyperparameters=[
            hp("n_clusters", "int", 3, 2, 10, description="Number of latent classes."),
            hp("n_init", "int", 10, 1, 30, tune=False, description="EM restarts; keeps the best by likelihood."),
            hp("random_state", "fixed", 42, tune=False),
        ],
        metrics=METRICS + ["aic", "bic"],
        min_rows=100,
        tags=["soft_clustering", "categorical"],
    ),
    spec(
        key="fuzzy_cmeans",
        name="Fuzzy C-Means",
        category="clustering",
        family="probabilistic",
        task_types=CLU,
        builder=lazy("dsai.registry.adapters:FuzzyCMeans"),
        module="sklearn",
        requires_scaling=True,
        interpretability=MODERATE,
        cost=Cost.MEDIUM,
        assumptions=["Clusters overlap and membership is a matter of degree"],
        advantages=["Every row gets a membership percentage in every segment", "Honest about borderline cases"],
        limitations=["Still assumes roughly spherical clusters", "The fuzziness exponent must be chosen"],
        good_for=["overlapping customer segments", "marketing personas"],
        hyperparameters=[
            hp("n_clusters", "int", 3, 2, 15),
            hp("m", "float", 2.0, 1.1, 3.0, description="Fuzziness. 1 approaches hard K-Means; higher is fuzzier."),
            hp("random_state", "fixed", 42, tune=False),
        ],
        metrics=METRICS,
        tags=["soft_clustering"],
    ),
    spec(
        key="spectral_clustering",
        name="Spectral Clustering",
        category="clustering",
        family="graph",
        task_types=CLU,
        builder=lazy("sklearn.cluster:SpectralClustering"),
        requires_scaling=True,
        interpretability=OPAQUE,
        cost=Cost.VERY_HIGH,
        nonlinear=True,
        max_recommended_rows=5000,
        assumptions=["Clusters are connected in a similarity graph, not necessarily compact"],
        advantages=["Separates interlocking, non-convex shapes that K-Means cannot"],
        limitations=["O(n³) eigen-decomposition", "No way to assign new points without refitting"],
        good_for=["non-convex clusters", "graph-like data"],
        hyperparameters=[
            hp("n_clusters", "int", 3, 2, 12),
            hp("affinity", "categorical", "rbf", choices=["rbf", "nearest_neighbors"]),
            hp("random_state", "fixed", 42, tune=False),
        ],
        metrics=METRICS,
    ),
    spec(
        key="affinity_propagation",
        name="Affinity Propagation",
        category="clustering",
        family="graph",
        task_types=CLU,
        builder=lazy("sklearn.cluster:AffinityPropagation"),
        requires_scaling=True,
        interpretability=MODERATE,
        cost=Cost.VERY_HIGH,
        max_recommended_rows=3000,
        advantages=["Chooses the number of clusters itself", "Exemplars are real observations"],
        limitations=["O(n²) memory and time", "Often produces far too many clusters"],
        good_for=["small datasets where k is genuinely unknown"],
        hyperparameters=[
            hp("damping", "float", 0.7, 0.5, 0.99, description="Higher damping stabilises convergence."),
            hp("random_state", "fixed", 42, tune=False),
        ],
        metrics=METRICS,
    ),
]

for _spec in SPECS:
    register(_spec, replace=True)

_LOADED = True
