"""Dimensionality reduction pack."""

from __future__ import annotations

from dsai.core.schema import TaskType
from dsai.registry._helpers import MODERATE, OPAQUE, TRANSPARENT, hp, lazy, spec
from dsai.registry.base import Cost, register

DR = [TaskType.DIMENSIONALITY_REDUCTION]
METRICS = ["explained_variance_ratio", "reconstruction_error", "trustworthiness"]

SPECS = [
    spec(
        key="pca",
        name="Principal Component Analysis",
        category="dimensionality_reduction",
        family="linear",
        task_types=DR,
        builder=lazy("sklearn.decomposition:PCA"),
        requires_scaling=True,
        interpretability=MODERATE,
        cost=Cost.LOW,
        assumptions=["Linear structure", "Variance equals information", "Features standardised first"],
        advantages=["Fast and deterministic", "Components can be interpreted through their loadings", "Explained variance quantifies what was kept"],
        limitations=["Only captures linear structure", "Components mix original variables, which blurs meaning"],
        good_for=["multicollinearity", "visualisation", "noise reduction", "compression"],
        hyperparameters=[
            hp("n_components", "int", 2, 2, 50, description="How many components to keep."),
            hp("random_state", "fixed", 42, tune=False),
        ],
        metrics=METRICS,
        tags=["workhorse"],
    ),
    spec(
        key="kernel_pca",
        name="Kernel PCA",
        category="dimensionality_reduction",
        family="kernel",
        task_types=DR,
        builder=lazy("sklearn.decomposition:KernelPCA"),
        requires_scaling=True,
        interpretability=OPAQUE,
        cost=Cost.HIGH,
        nonlinear=True,
        max_recommended_rows=5000,
        advantages=["Captures curved structure that linear PCA misses"],
        limitations=["No explained-variance interpretation", "Kernel and gamma must be chosen", "O(n²) memory"],
        good_for=["nonlinear manifolds"],
        hyperparameters=[
            hp("n_components", "int", 2, 2, 20),
            hp("kernel", "categorical", "rbf", choices=["rbf", "poly", "cosine", "sigmoid"]),
            hp("gamma", "float", None, 0.001, 1.0, log=True),
            hp("random_state", "fixed", 42, tune=False),
        ],
        metrics=["trustworthiness"],
    ),
    spec(
        key="truncated_svd",
        name="Truncated SVD (LSA)",
        category="dimensionality_reduction",
        family="linear",
        task_types=DR,
        builder=lazy("sklearn.decomposition:TruncatedSVD"),
        requires_scaling=False,
        interpretability=MODERATE,
        cost=Cost.LOW,
        handles_high_dimensionality=True,
        advantages=["Works directly on sparse matrices, unlike PCA", "The standard choice for text/TF-IDF"],
        limitations=["Does not centre the data, so components differ from PCA"],
        good_for=["sparse data", "text", "very wide matrices"],
        hyperparameters=[hp("n_components", "int", 2, 2, 50), hp("random_state", "fixed", 42, tune=False)],
        metrics=METRICS,
        tags=["sparse", "text"],
    ),
    spec(
        key="fastica",
        name="Independent Component Analysis",
        category="dimensionality_reduction",
        family="linear",
        task_types=DR,
        builder=lazy("sklearn.decomposition:FastICA"),
        requires_scaling=True,
        interpretability=MODERATE,
        cost=Cost.MEDIUM,
        assumptions=["Observed variables are linear mixtures of statistically independent, non-Gaussian sources"],
        advantages=["Separates mixed signals rather than maximising variance"],
        limitations=["Component order and sign are arbitrary", "Can fail to converge"],
        good_for=["signal separation", "sensor data"],
        hyperparameters=[
            hp("n_components", "int", 2, 2, 20),
            hp("max_iter", "fixed", 500, tune=False),
            hp("random_state", "fixed", 42, tune=False),
        ],
        metrics=["reconstruction_error"],
    ),
    spec(
        key="nmf",
        name="Non-negative Matrix Factorisation",
        category="dimensionality_reduction",
        family="linear",
        task_types=DR,
        builder=lazy("sklearn.decomposition:NMF"),
        requires_scaling=False,
        interpretability=TRANSPARENT,
        cost=Cost.MEDIUM,
        assumptions=["All input values are non-negative"],
        advantages=["Parts-based, additive components that read as topics or themes"],
        limitations=["Fails on any negative value", "Solution depends on initialisation"],
        good_for=["topic modelling", "basket/spend composition", "non-negative data"],
        hyperparameters=[
            hp("n_components", "int", 3, 2, 30),
            hp("init", "fixed", "nndsvda", tune=False),
            hp("max_iter", "fixed", 500, tune=False),
            hp("random_state", "fixed", 42, tune=False),
        ],
        metrics=["reconstruction_error"],
        tags=["topics"],
    ),
    spec(
        key="factor_analysis",
        name="Factor Analysis",
        category="dimensionality_reduction",
        family="statistical",
        task_types=DR,
        builder=lazy("sklearn.decomposition:FactorAnalysis"),
        requires_scaling=True,
        interpretability=MODERATE,
        cost=Cost.MEDIUM,
        assumptions=["Observed variables are driven by a few latent factors plus per-variable noise"],
        advantages=["Explicitly models measurement error, unlike PCA", "The standard tool for survey and psychometric data"],
        limitations=["Factors need rotation and judgement to name", "Assumes linear, Gaussian structure"],
        good_for=["survey data", "construct measurement", "psychometrics"],
        hyperparameters=[
            hp("n_components", "int", 2, 1, 20),
            hp("rotation", "categorical", "varimax", choices=[None, "varimax", "quartimax"]),
            hp("random_state", "fixed", 42, tune=False),
        ],
        metrics=["loglikelihood"],
        tags=["survey"],
    ),
    spec(
        key="lda_projection",
        name="Linear Discriminant Analysis (supervised projection)",
        category="dimensionality_reduction",
        family="statistical",
        task_types=DR,
        builder=lazy("sklearn.discriminant_analysis:LinearDiscriminantAnalysis"),
        requires_scaling=True,
        interpretability=MODERATE,
        cost=Cost.LOW,
        assumptions=["Labelled data available", "Shared class covariance"],
        advantages=["Projects to the directions that separate known classes best"],
        limitations=["Needs labels", "At most (classes − 1) dimensions"],
        good_for=["supervised visualisation", "pre-classification compression"],
        hyperparameters=[hp("n_components", "int", 2, 1, 10)],
        metrics=["explained_variance_ratio"],
        tags=["supervised"],
    ),
    spec(
        key="tsne",
        name="t-SNE",
        category="dimensionality_reduction",
        family="manifold",
        task_types=DR,
        builder=lazy("sklearn.manifold:TSNE"),
        requires_scaling=True,
        interpretability=OPAQUE,
        cost=Cost.VERY_HIGH,
        nonlinear=True,
        max_recommended_rows=10000,
        assumptions=["Only local neighbourhood structure is meaningful"],
        advantages=["Outstanding for revealing clusters visually"],
        limitations=[
            "Distances between clusters on the plot are NOT meaningful",
            "Cluster sizes on the plot are NOT meaningful",
            "Different perplexity values give different pictures — never use it as evidence on its own",
        ],
        good_for=["2D visualisation of cluster structure"],
        hyperparameters=[
            hp("n_components", "fixed", 2, tune=False),
            hp("perplexity", "float", 30.0, 5.0, 50.0, description="Roughly the number of neighbours considered."),
            hp("learning_rate", "categorical", "auto", choices=["auto", 200.0]),
            hp("random_state", "fixed", 42, tune=False),
        ],
        metrics=["trustworthiness"],
        tags=["visualisation_only"],
    ),
    spec(
        key="umap",
        name="UMAP",
        category="dimensionality_reduction",
        family="manifold",
        task_types=DR,
        builder=lazy("umap:UMAP"),
        module="umap",
        requires_scaling=True,
        interpretability=OPAQUE,
        cost=Cost.HIGH,
        nonlinear=True,
        advantages=["Much faster than t-SNE", "Preserves more of the global structure", "Can transform new rows"],
        limitations=["Still a projection — do not read exact distances off the plot", "Extra dependency"],
        good_for=["visualisation", "nonlinear feature compression"],
        hyperparameters=[
            hp("n_components", "int", 2, 2, 20),
            hp("n_neighbors", "int", 15, 5, 100, description="Balance of local vs global structure."),
            hp("min_dist", "float", 0.1, 0.0, 0.99, description="How tightly points may pack together."),
            hp("random_state", "fixed", 42, tune=False),
        ],
        metrics=["trustworthiness"],
        tags=["visualisation"],
    ),
    spec(
        key="isomap",
        name="Isomap",
        category="dimensionality_reduction",
        family="manifold",
        task_types=DR,
        builder=lazy("sklearn.manifold:Isomap"),
        requires_scaling=True,
        interpretability=OPAQUE,
        cost=Cost.HIGH,
        nonlinear=True,
        max_recommended_rows=5000,
        advantages=["Preserves geodesic distances along a curved manifold"],
        limitations=["Sensitive to the neighbourhood size", "Breaks if the neighbour graph is disconnected"],
        good_for=["smooth nonlinear manifolds"],
        hyperparameters=[hp("n_components", "int", 2, 2, 20), hp("n_neighbors", "int", 5, 3, 50)],
        metrics=["reconstruction_error"],
    ),
    spec(
        key="mds",
        name="Multidimensional Scaling",
        category="dimensionality_reduction",
        family="manifold",
        task_types=DR,
        builder=lazy("sklearn.manifold:MDS"),
        requires_scaling=True,
        interpretability=OPAQUE,
        cost=Cost.VERY_HIGH,
        nonlinear=True,
        max_recommended_rows=3000,
        advantages=["Lays points out so plotted distances match real distances as closely as possible"],
        limitations=["O(n²)", "No way to project new points"],
        good_for=["similarity/perceptual maps"],
        hyperparameters=[hp("n_components", "int", 2, 2, 10), hp("random_state", "fixed", 42, tune=False)],
        metrics=["stress"],
    ),
]

for _spec in SPECS:
    register(_spec, replace=True)

_LOADED = True
