"""Regression algorithm pack."""

from __future__ import annotations

from dsai.core.schema import TaskType
from dsai.registry._helpers import (
    MODERATE, OPAQUE, TRANSPARENT, boosting_params, forest_params, hp, lazy, spec, tree_params,
)
from dsai.registry.base import Cost, register

REG = [TaskType.REGRESSION]
METRICS = ["r2", "rmse", "mae", "mape", "explained_variance"]

SPECS = [
    spec(
        key="linear_regression",
        name="Linear Regression (OLS)",
        category="regression",
        family="linear",
        task_types=REG,
        builder=lazy("sklearn.linear_model:LinearRegression"),
        requires_scaling=False,
        supports_coefficients=True,
        interpretability=TRANSPARENT,
        cost=Cost.VERY_LOW,
        complexity="O(n·p²)",
        baseline=True,
        assumptions=[
            "Relationship between predictors and target is roughly straight-line",
            "Residuals are independent, roughly normal, and of constant variance",
            "Predictors are not near-perfectly correlated with each other",
        ],
        advantages=["Coefficients read directly as effect sizes", "Instant to fit", "Well-understood inference"],
        limitations=["Cannot capture curves or interactions unless you build them", "Sensitive to outliers and multicollinearity"],
        good_for=["explanatory analysis", "baseline", "small clean datasets"],
        hyperparameters=[hp("fit_intercept", "bool", True, tune=False)],
        metrics=METRICS,
        tags=["baseline", "explanatory"],
        docs_url="https://scikit-learn.org/stable/modules/linear_model.html",
    ),
    spec(
        key="ridge",
        name="Ridge Regression (L2)",
        category="regression",
        family="linear",
        task_types=REG,
        builder=lazy("sklearn.linear_model:Ridge"),
        requires_scaling=True,
        supports_coefficients=True,
        interpretability=TRANSPARENT,
        cost=Cost.VERY_LOW,
        handles_high_dimensionality=True,
        assumptions=["Linear relationship", "Predictors standardised before fitting"],
        advantages=["Stabilises coefficients when predictors are correlated", "Rarely overfits"],
        limitations=["Keeps every variable — no automatic selection", "Coefficients are shrunk, so slightly biased"],
        good_for=["multicollinearity", "wide datasets"],
        hyperparameters=[
            hp("alpha", "float", 1.0, 0.001, 100.0, log=True, description="Strength of the shrinkage penalty."),
            hp("random_state", "fixed", 42, tune=False),
        ],
        metrics=METRICS,
        tags=["regularised"],
    ),
    spec(
        key="lasso",
        name="Lasso Regression (L1)",
        category="regression",
        family="linear",
        task_types=REG,
        builder=lazy("sklearn.linear_model:Lasso"),
        requires_scaling=True,
        supports_coefficients=True,
        interpretability=TRANSPARENT,
        cost=Cost.VERY_LOW,
        handles_high_dimensionality=True,
        assumptions=["Linear relationship", "Only a subset of predictors truly matter"],
        advantages=["Performs feature selection by driving coefficients to zero", "Produces sparse, readable models"],
        limitations=["Arbitrarily picks one of a group of correlated predictors", "Can under-fit if the true model is dense"],
        good_for=["feature selection", "wide datasets"],
        hyperparameters=[
            hp("alpha", "float", 0.1, 0.0001, 10.0, log=True, description="Higher values zero out more variables."),
            hp("max_iter", "fixed", 5000, tune=False),
            hp("random_state", "fixed", 42, tune=False),
        ],
        metrics=METRICS,
        tags=["regularised", "feature_selection"],
    ),
    spec(
        key="elastic_net",
        name="Elastic Net",
        category="regression",
        family="linear",
        task_types=REG,
        builder=lazy("sklearn.linear_model:ElasticNet"),
        requires_scaling=True,
        supports_coefficients=True,
        interpretability=TRANSPARENT,
        cost=Cost.LOW,
        handles_high_dimensionality=True,
        assumptions=["Linear relationship"],
        advantages=["Blends Ridge and Lasso", "Handles groups of correlated predictors sensibly"],
        limitations=["Two hyper-parameters to tune", "Still a linear model"],
        good_for=["multicollinearity", "feature selection"],
        hyperparameters=[
            hp("alpha", "float", 0.1, 0.0001, 10.0, log=True, description="Overall penalty strength."),
            hp("l1_ratio", "float", 0.5, 0.05, 0.95, description="0 = pure Ridge, 1 = pure Lasso."),
            hp("max_iter", "fixed", 5000, tune=False),
            hp("random_state", "fixed", 42, tune=False),
        ],
        metrics=METRICS,
        tags=["regularised"],
    ),
    spec(
        key="bayesian_ridge",
        name="Bayesian Ridge Regression",
        category="regression",
        family="probabilistic",
        task_types=REG,
        builder=lazy("sklearn.linear_model:BayesianRidge"),
        requires_scaling=True,
        supports_coefficients=True,
        interpretability=TRANSPARENT,
        cost=Cost.LOW,
        assumptions=["Linear relationship", "Gaussian noise"],
        advantages=["Estimates the regularisation strength from the data", "Gives predictive uncertainty"],
        limitations=["Assumes normal errors", "Still linear"],
        good_for=["small datasets", "uncertainty quantification"],
        hyperparameters=[hp("max_iter", "int", 300, 100, 1000, tune=False)],
        metrics=METRICS,
        tags=["uncertainty"],
    ),
    spec(
        key="huber",
        name="Huber Regression (robust)",
        category="regression",
        family="linear",
        task_types=REG,
        builder=lazy("sklearn.linear_model:HuberRegressor"),
        requires_scaling=True,
        supports_coefficients=True,
        interpretability=TRANSPARENT,
        cost=Cost.LOW,
        robust_to_outliers=True,
        assumptions=["Mostly linear relationship with a minority of contaminated points"],
        advantages=["Outliers pull the fit far less than OLS", "Still gives readable coefficients"],
        limitations=["Slower than OLS", "Needs the epsilon threshold chosen sensibly"],
        good_for=["outlier-heavy data"],
        hyperparameters=[
            hp("epsilon", "float", 1.35, 1.05, 3.0, description="Lower is more robust; 1.35 covers ~95% of normal data."),
            hp("alpha", "float", 0.0001, 1e-6, 1.0, log=True),
            hp("max_iter", "fixed", 500, tune=False),
        ],
        metrics=METRICS,
        tags=["robust"],
    ),
    spec(
        key="quantile_regression",
        name="Quantile Regression",
        category="regression",
        family="linear",
        task_types=REG,
        builder=lazy("sklearn.linear_model:QuantileRegressor"),
        requires_scaling=True,
        supports_coefficients=True,
        interpretability=TRANSPARENT,
        cost=Cost.MEDIUM,
        robust_to_outliers=True,
        assumptions=["Linear effect on the chosen quantile of the target"],
        advantages=["Models the median or any percentile, not just the mean", "Naturally robust"],
        limitations=["Slow on large data", "One fit per quantile of interest"],
        good_for=["skewed targets", "prediction intervals"],
        hyperparameters=[
            hp("quantile", "float", 0.5, 0.05, 0.95, description="Which percentile of the target to model."),
            hp("alpha", "float", 0.0, 0.0, 1.0),
            hp("solver", "fixed", "highs", tune=False),
        ],
        metrics=["mae", "rmse", "pinball_loss"],
        tags=["robust", "uncertainty"],
    ),
    spec(
        key="poisson_regression",
        name="Poisson Regression (GLM)",
        category="regression",
        family="statistical",
        task_types=REG,
        builder=lazy("sklearn.linear_model:PoissonRegressor"),
        requires_scaling=True,
        supports_coefficients=True,
        interpretability=TRANSPARENT,
        cost=Cost.LOW,
        assumptions=["Target is a non-negative count", "Mean and variance are comparable"],
        advantages=["Correct likelihood for count outcomes", "Coefficients read as rate multipliers"],
        limitations=["Fails on negative targets", "Over-dispersed counts need a Negative Binomial or Gamma model"],
        good_for=["count data", "event rates"],
        hyperparameters=[hp("alpha", "float", 1.0, 0.0, 10.0), hp("max_iter", "fixed", 300, tune=False)],
        metrics=["poisson_deviance", "mae", "rmse"],
        tags=["glm", "count"],
    ),
    spec(
        key="gamma_regression",
        name="Gamma Regression (GLM)",
        category="regression",
        family="statistical",
        task_types=REG,
        builder=lazy("sklearn.linear_model:GammaRegressor"),
        requires_scaling=True,
        supports_coefficients=True,
        interpretability=TRANSPARENT,
        cost=Cost.LOW,
        assumptions=["Target is strictly positive", "Variance grows with the mean"],
        advantages=["Right likelihood for positive, right-skewed amounts such as claim sizes or spend"],
        limitations=["Target must be > 0", "Log link makes coefficients multiplicative, not additive"],
        good_for=["monetary amounts", "duration data"],
        hyperparameters=[hp("alpha", "float", 1.0, 0.0, 10.0), hp("max_iter", "fixed", 300, tune=False)],
        metrics=["gamma_deviance", "mae", "rmse"],
        tags=["glm", "positive_target"],
    ),
    spec(
        key="tweedie_regression",
        name="Tweedie Regression (GLM)",
        category="regression",
        family="statistical",
        task_types=REG,
        builder=lazy("sklearn.linear_model:TweedieRegressor"),
        requires_scaling=True,
        supports_coefficients=True,
        interpretability=TRANSPARENT,
        cost=Cost.LOW,
        assumptions=["Target is non-negative, often with a spike at zero"],
        advantages=["Handles zero-inflated positive amounts (insurance, spend) in one model"],
        limitations=["The power parameter must be chosen deliberately"],
        good_for=["zero-inflated amounts"],
        hyperparameters=[
            hp("power", "float", 1.5, 0.0, 2.0, description="0=normal, 1=Poisson, 2=Gamma, 1-2=compound Poisson-Gamma."),
            hp("alpha", "float", 1.0, 0.0, 10.0),
            hp("max_iter", "fixed", 300, tune=False),
        ],
        metrics=["mae", "rmse"],
        tags=["glm"],
    ),
    spec(
        key="ols_statsmodels",
        name="OLS with full inference (statsmodels)",
        category="regression",
        family="statistical",
        task_types=REG,
        builder=lazy("dsai.registry.adapters:StatsmodelsOLS"),
        module="statsmodels",
        requires_scaling=False,
        supports_coefficients=True,
        interpretability=TRANSPARENT,
        cost=Cost.LOW,
        assumptions=["Standard OLS assumptions (linearity, independence, homoscedasticity, normal residuals)"],
        advantages=["p-values, standard errors and confidence intervals for every coefficient", "Full diagnostic suite"],
        limitations=["No regularisation", "Breaks down with perfectly collinear predictors"],
        good_for=["hypothesis testing", "explanatory analysis", "academic reporting"],
        hyperparameters=[],
        metrics=METRICS,
        tags=["inference", "explanatory"],
    ),
    spec(
        key="polynomial_regression",
        name="Polynomial Regression",
        category="regression",
        family="linear",
        task_types=REG,
        builder=lazy("dsai.registry.adapters:PolynomialRegressor"),
        requires_scaling=True,
        supports_coefficients=True,
        interpretability=MODERATE,
        cost=Cost.LOW,
        nonlinear=True,
        assumptions=["Relationship is a smooth curve of the chosen degree"],
        advantages=["Captures curvature while staying a linear model underneath"],
        limitations=["Explodes in width with many features", "Extrapolates wildly outside the observed range"],
        good_for=["curved relationships", "few predictors"],
        hyperparameters=[
            hp("degree", "int", 2, 2, 4, description="Highest power of each predictor."),
            hp("alpha", "float", 1.0, 0.0001, 100.0, log=True, description="Ridge penalty on the expanded features."),
        ],
        metrics=METRICS,
        tags=["nonlinear"],
        max_recommended_features=30,
    ),
    spec(
        key="pls_regression",
        name="Partial Least Squares",
        category="regression",
        family="linear",
        task_types=REG,
        builder=lazy("sklearn.cross_decomposition:PLSRegression"),
        requires_scaling=True,
        supports_coefficients=True,
        interpretability=MODERATE,
        cost=Cost.LOW,
        handles_high_dimensionality=True,
        assumptions=["Linear structure captured by a few latent components"],
        advantages=["Works when there are more predictors than rows", "Handles severe multicollinearity"],
        limitations=["Components are combinations, so harder to explain than raw coefficients"],
        good_for=["wide datasets", "spectroscopy-style data", "multicollinearity"],
        hyperparameters=[hp("n_components", "int", 2, 1, 10, description="Number of latent components to extract.")],
        metrics=METRICS,
        tags=["latent"],
    ),
    spec(
        key="decision_tree_regressor",
        name="Decision Tree Regressor",
        category="regression",
        family="tree",
        task_types=REG,
        builder=lazy("sklearn.tree:DecisionTreeRegressor"),
        requires_scaling=False,
        supports_feature_importance=True,
        interpretability=TRANSPARENT,
        cost=Cost.LOW,
        nonlinear=True,
        robust_to_outliers=True,
        assumptions=["None — the tree makes no distributional assumptions"],
        advantages=["The whole model can be drawn and read as if-then rules", "No scaling needed"],
        limitations=["A single tree is unstable — small data changes redraw it", "Predicts in steps, not smooth curves"],
        good_for=["rule extraction", "explaining segments"],
        hyperparameters=tree_params(5) + [hp("random_state", "fixed", 42, tune=False)],
        metrics=METRICS,
        tags=["rules"],
    ),
    spec(
        key="random_forest_regressor",
        name="Random Forest Regressor",
        category="regression",
        family="ensemble",
        task_types=REG,
        builder=lazy("sklearn.ensemble:RandomForestRegressor"),
        requires_scaling=False,
        supports_feature_importance=True,
        interpretability=MODERATE,
        cost=Cost.MEDIUM,
        nonlinear=True,
        robust_to_outliers=True,
        assumptions=["None"],
        advantages=["Strong out of the box", "Handles nonlinearity and interactions automatically", "Little preprocessing"],
        limitations=["Cannot extrapolate beyond the training range", "Slower and larger than a linear model"],
        good_for=["general-purpose prediction", "nonlinear relationships", "mixed data types"],
        hyperparameters=forest_params(),
        metrics=METRICS,
        tags=["workhorse"],
    ),
    spec(
        key="extra_trees_regressor",
        name="Extra Trees Regressor",
        category="regression",
        family="ensemble",
        task_types=REG,
        builder=lazy("sklearn.ensemble:ExtraTreesRegressor"),
        requires_scaling=False,
        supports_feature_importance=True,
        interpretability=MODERATE,
        cost=Cost.MEDIUM,
        nonlinear=True,
        robust_to_outliers=True,
        advantages=["Faster than Random Forest", "Extra randomness often lowers variance further"],
        limitations=["Slightly more biased than Random Forest", "Same inability to extrapolate"],
        good_for=["noisy data", "fast nonlinear baselines"],
        hyperparameters=forest_params(),
        metrics=METRICS,
    ),
    spec(
        key="gradient_boosting_regressor",
        name="Gradient Boosting Regressor",
        category="regression",
        family="ensemble",
        task_types=REG,
        builder=lazy("sklearn.ensemble:GradientBoostingRegressor"),
        requires_scaling=False,
        supports_feature_importance=True,
        interpretability=MODERATE,
        cost=Cost.HIGH,
        nonlinear=True,
        advantages=["Usually the strongest accuracy on tabular data", "Captures subtle interactions"],
        limitations=["Overfits if left untuned", "Sequential, so slower to train"],
        good_for=["maximum accuracy", "tabular prediction"],
        hyperparameters=boosting_params(),
        metrics=METRICS,
        tags=["high_accuracy"],
    ),
    spec(
        key="hist_gradient_boosting_regressor",
        name="Histogram Gradient Boosting Regressor",
        category="regression",
        family="ensemble",
        task_types=REG,
        builder=lazy("sklearn.ensemble:HistGradientBoostingRegressor"),
        requires_scaling=False,
        handles_missing=True,
        supports_feature_importance=False,
        interpretability=MODERATE,
        cost=Cost.MEDIUM,
        nonlinear=True,
        advantages=["Handles missing values natively", "Much faster than classic boosting on large data"],
        limitations=["No built-in feature importances (use permutation importance)"],
        good_for=["large datasets", "data with missing values"],
        hyperparameters=[
            hp("max_iter", "int", 300, 50, 1000),
            hp("learning_rate", "float", 0.1, 0.01, 0.3, log=True),
            hp("max_depth", "int", None, 2, 15),
            hp("l2_regularization", "float", 0.0, 0.0, 10.0),
            hp("random_state", "fixed", 42, tune=False),
        ],
        metrics=METRICS,
        tags=["fast", "missing_tolerant"],
    ),
    spec(
        key="adaboost_regressor",
        name="AdaBoost Regressor",
        category="regression",
        family="ensemble",
        task_types=REG,
        builder=lazy("sklearn.ensemble:AdaBoostRegressor"),
        requires_scaling=False,
        supports_feature_importance=True,
        interpretability=MODERATE,
        cost=Cost.MEDIUM,
        nonlinear=True,
        advantages=["Simple boosting scheme with few knobs"],
        limitations=["Very sensitive to noisy targets and outliers"],
        good_for=["clean, moderate-size data"],
        hyperparameters=[
            hp("n_estimators", "int", 200, 50, 800),
            hp("learning_rate", "float", 1.0, 0.01, 2.0, log=True),
            hp("random_state", "fixed", 42, tune=False),
        ],
        metrics=METRICS,
    ),
    spec(
        key="bagging_regressor",
        name="Bagging Regressor",
        category="regression",
        family="ensemble",
        task_types=REG,
        builder=lazy("sklearn.ensemble:BaggingRegressor"),
        requires_scaling=False,
        interpretability=OPAQUE,
        cost=Cost.MEDIUM,
        nonlinear=True,
        advantages=["Cuts the variance of any unstable base learner"],
        limitations=["No bias reduction", "Loses the base model's interpretability"],
        good_for=["stabilising high-variance models"],
        hyperparameters=[hp("n_estimators", "int", 50, 10, 300), hp("random_state", "fixed", 42, tune=False)],
        metrics=METRICS,
    ),
    spec(
        key="xgboost_regressor",
        name="XGBoost Regressor",
        category="regression",
        family="ensemble",
        task_types=REG,
        builder=lazy("xgboost:XGBRegressor"),
        module="xgboost",
        requires_scaling=False,
        handles_missing=True,
        supports_feature_importance=True,
        interpretability=MODERATE,
        cost=Cost.MEDIUM,
        nonlinear=True,
        advantages=["Consistently top-tier on tabular data", "Handles missing values internally", "Rich regularisation"],
        limitations=["Many hyper-parameters", "Needs an extra dependency"],
        good_for=["competitions", "maximum accuracy", "large tabular data"],
        hyperparameters=boosting_params() + [
            hp("reg_lambda", "float", 1.0, 0.0, 10.0, description="L2 penalty on leaf weights."),
            hp("colsample_bytree", "float", 1.0, 0.4, 1.0),
            hp("n_jobs", "fixed", -1, tune=False),
        ],
        metrics=METRICS,
        tags=["high_accuracy", "missing_tolerant"],
    ),
    spec(
        key="lightgbm_regressor",
        name="LightGBM Regressor",
        category="regression",
        family="ensemble",
        task_types=REG,
        builder=lazy("lightgbm:LGBMRegressor"),
        module="lightgbm",
        requires_scaling=False,
        handles_missing=True,
        handles_categorical=True,
        supports_feature_importance=True,
        interpretability=MODERATE,
        cost=Cost.LOW,
        nonlinear=True,
        advantages=["Very fast on large data", "Native categorical and missing handling"],
        limitations=["Leaf-wise growth overfits small datasets", "Needs an extra dependency"],
        good_for=["large datasets", "many categorical features"],
        hyperparameters=[
            hp("n_estimators", "int", 300, 50, 1500),
            hp("learning_rate", "float", 0.05, 0.01, 0.3, log=True),
            hp("num_leaves", "int", 31, 8, 255),
            hp("min_child_samples", "int", 20, 5, 100),
            hp("random_state", "fixed", 42, tune=False),
            hp("verbose", "fixed", -1, tune=False),
            hp("n_jobs", "fixed", -1, tune=False),
        ],
        metrics=METRICS,
        tags=["fast", "high_accuracy"],
        min_rows=100,
    ),
    spec(
        key="catboost_regressor",
        name="CatBoost Regressor",
        category="regression",
        family="ensemble",
        task_types=REG,
        builder=lazy("catboost:CatBoostRegressor"),
        module="catboost",
        requires_scaling=False,
        handles_missing=True,
        handles_categorical=True,
        supports_feature_importance=True,
        interpretability=MODERATE,
        cost=Cost.HIGH,
        nonlinear=True,
        advantages=["Best-in-class categorical handling", "Strong defaults with little tuning"],
        limitations=["Slow to train", "Large dependency"],
        good_for=["categorical-heavy data"],
        hyperparameters=[
            hp("iterations", "int", 500, 100, 2000),
            hp("learning_rate", "float", 0.05, 0.01, 0.3, log=True),
            hp("depth", "int", 6, 3, 10),
            hp("verbose", "fixed", 0, tune=False),
            hp("random_seed", "fixed", 42, tune=False),
        ],
        metrics=METRICS,
    ),
    spec(
        key="svr_rbf",
        name="Support Vector Regression (RBF kernel)",
        category="regression",
        family="kernel",
        task_types=REG,
        builder=lazy("sklearn.svm:SVR"),
        requires_scaling=True,
        interpretability=OPAQUE,
        cost=Cost.HIGH,
        nonlinear=True,
        robust_to_outliers=True,
        max_recommended_rows=20000,
        assumptions=["Features are on a comparable scale"],
        advantages=["Captures smooth nonlinearity well on modest datasets", "Epsilon-tube ignores small errors"],
        limitations=["Scales badly past ~20k rows", "No direct interpretation", "Scaling is mandatory"],
        good_for=["small to medium nonlinear problems"],
        hyperparameters=[
            hp("C", "float", 1.0, 0.01, 100.0, log=True, description="Higher C fits the training data harder."),
            hp("epsilon", "float", 0.1, 0.01, 1.0, description="Errors inside this tube cost nothing."),
            hp("gamma", "categorical", "scale", choices=["scale", "auto", 0.01, 0.1]),
            hp("kernel", "fixed", "rbf", tune=False),
        ],
        metrics=METRICS,
    ),
    spec(
        key="svr_linear",
        name="Linear Support Vector Regression",
        category="regression",
        family="kernel",
        task_types=REG,
        builder=lazy("sklearn.svm:LinearSVR"),
        requires_scaling=True,
        supports_coefficients=True,
        interpretability=MODERATE,
        cost=Cost.LOW,
        robust_to_outliers=True,
        advantages=["Fast linear alternative to SVR", "Robust loss function"],
        limitations=["Linear only", "Needs scaling"],
        good_for=["large linear problems"],
        hyperparameters=[
            hp("C", "float", 1.0, 0.01, 100.0, log=True),
            hp("epsilon", "float", 0.0, 0.0, 1.0),
            hp("max_iter", "fixed", 5000, tune=False),
            hp("random_state", "fixed", 42, tune=False),
        ],
        metrics=METRICS,
    ),
    spec(
        key="knn_regressor",
        name="K-Nearest Neighbours Regressor",
        category="regression",
        family="distance",
        task_types=REG,
        builder=lazy("sklearn.neighbors:KNeighborsRegressor"),
        requires_scaling=True,
        interpretability=MODERATE,
        cost=Cost.LOW,
        nonlinear=True,
        max_recommended_features=50,
        assumptions=["Similar rows have similar targets", "Distances are meaningful, so features must be scaled"],
        advantages=["No training phase", "Naturally local — explains a prediction by its neighbours"],
        limitations=["Degrades badly in high dimensions", "Prediction is slow on big data"],
        good_for=["local patterns", "small feature sets"],
        hyperparameters=[
            hp("n_neighbors", "int", 5, 1, 50, description="How many neighbours to average."),
            hp("weights", "categorical", "uniform", choices=["uniform", "distance"]),
            hp("p", "categorical", 2, choices=[1, 2], description="1 = Manhattan, 2 = Euclidean."),
        ],
        metrics=METRICS,
    ),
    spec(
        key="gaussian_process_regressor",
        name="Gaussian Process Regression",
        category="regression",
        family="probabilistic",
        task_types=REG,
        builder=lazy("sklearn.gaussian_process:GaussianProcessRegressor"),
        requires_scaling=True,
        interpretability=OPAQUE,
        cost=Cost.VERY_HIGH,
        nonlinear=True,
        max_recommended_rows=2000,
        assumptions=["Smooth underlying function", "Gaussian noise"],
        advantages=["Principled uncertainty on every prediction", "Excellent on very small datasets"],
        limitations=["O(n³) — unusable beyond a few thousand rows", "Kernel choice matters a lot"],
        good_for=["small datasets", "uncertainty quantification", "experimental design"],
        hyperparameters=[
            hp("alpha", "float", 1e-8, 1e-10, 1.0, log=True, description="Assumed noise level."),
            hp("normalize_y", "bool", True, tune=False),
            hp("random_state", "fixed", 42, tune=False),
        ],
        metrics=METRICS,
        tags=["uncertainty"],
    ),
    spec(
        key="mlp_regressor",
        name="Neural Network Regressor (MLP)",
        category="regression",
        family="neural",
        task_types=REG,
        builder=lazy("sklearn.neural_network:MLPRegressor"),
        requires_scaling=True,
        interpretability=OPAQUE,
        cost=Cost.HIGH,
        nonlinear=True,
        min_rows=200,
        assumptions=["Enough rows to estimate many weights", "Scaled inputs"],
        advantages=["Learns arbitrary smooth functions given enough data"],
        limitations=["Needs a lot of data", "Unstable without scaling", "Nothing to read directly"],
        good_for=["large datasets", "complex nonlinearity"],
        hyperparameters=[
            hp("hidden_layer_sizes", "categorical", (64, 32), choices=[(32,), (64, 32), (128, 64), (100,)]),
            hp("alpha", "float", 0.0001, 1e-6, 1.0, log=True, description="L2 weight penalty."),
            hp("learning_rate_init", "float", 0.001, 1e-4, 0.05, log=True),
            hp("max_iter", "fixed", 800, tune=False),
            hp("early_stopping", "fixed", True, tune=False),
            hp("random_state", "fixed", 42, tune=False),
        ],
        metrics=METRICS,
    ),
    spec(
        key="dummy_regressor",
        name="Baseline (predict the mean)",
        category="regression",
        family="baseline",
        task_types=REG,
        builder=lazy("sklearn.dummy:DummyRegressor"),
        requires_scaling=False,
        interpretability=TRANSPARENT,
        cost=Cost.VERY_LOW,
        baseline=True,
        min_rows=5,
        advantages=["Defines the score any real model must beat"],
        limitations=["Learns nothing — that is the point"],
        good_for=["sanity check"],
        hyperparameters=[hp("strategy", "categorical", "mean", choices=["mean", "median"])],
        metrics=METRICS,
        tags=["baseline"],
    ),
    spec(
        key="stacking_regressor",
        name="Stacking Ensemble Regressor",
        category="regression",
        family="ensemble",
        task_types=REG,
        builder=lazy("dsai.registry.adapters:DefaultStackingRegressor"),
        requires_scaling=True,
        interpretability=OPAQUE,
        cost=Cost.VERY_HIGH,
        nonlinear=True,
        min_rows=200,
        advantages=["Combines complementary models, often beating any single one"],
        limitations=["Expensive to train", "Very hard to explain", "Easy to overfit the meta-learner"],
        good_for=["squeezing out the last few points of accuracy"],
        hyperparameters=[hp("cv", "int", 5, 3, 10, tune=False)],
        metrics=METRICS,
        tags=["ensemble_of_ensembles"],
    ),
    spec(
        key="voting_regressor",
        name="Voting Ensemble Regressor",
        category="regression",
        family="ensemble",
        task_types=REG,
        builder=lazy("dsai.registry.adapters:DefaultVotingRegressor"),
        requires_scaling=True,
        interpretability=OPAQUE,
        cost=Cost.HIGH,
        nonlinear=True,
        min_rows=100,
        advantages=["Simple averaging of diverse models; usually beats the average member"],
        limitations=["Rarely beats a well-tuned single boosting model", "Slow"],
        good_for=["stability"],
        hyperparameters=[],
        metrics=METRICS,
    ),
]

for _spec in SPECS:
    register(_spec, replace=True)

_LOADED = True
