"""Time-series forecasting pack.

Every entry builds a :class:`~dsai.registry.ts_adapters.BaseForecaster`, so the
experiment engine can back-test statistical and machine-learning forecasters
through exactly the same interface.
"""

from __future__ import annotations

from dsai.core.schema import TaskType
from dsai.registry._helpers import MODERATE, OPAQUE, TRANSPARENT, hp, lazy, spec
from dsai.registry.base import Cost, register

TS = [TaskType.TIME_SERIES_FORECAST]
METRICS = ["rmse", "mae", "mape", "smape", "mase"]

SPECS = [
    spec(
        key="naive_forecast",
        name="Naive Forecast (last value)",
        category="time_series",
        family="baseline",
        task_types=TS,
        builder=lazy("dsai.registry.ts_adapters:NaiveForecaster"),
        module="pandas",
        interpretability=TRANSPARENT,
        cost=Cost.VERY_LOW,
        baseline=True,
        min_rows=5,
        assumptions=["Tomorrow looks like today"],
        advantages=["The benchmark every other forecast must beat", "Impossible to overfit"],
        limitations=["Ignores trend and seasonality"],
        good_for=["baseline", "random-walk series"],
        hyperparameters=[hp("seasonal_period", "int", None, 2, 52, description="Set this to repeat the last full season instead.")],
        metrics=METRICS,
        tags=["baseline"],
    ),
    spec(
        key="drift_forecast",
        name="Drift Forecast (linear extrapolation)",
        category="time_series",
        family="baseline",
        task_types=TS,
        builder=lazy("dsai.registry.ts_adapters:DriftForecaster"),
        module="pandas",
        interpretability=TRANSPARENT,
        cost=Cost.VERY_LOW,
        baseline=True,
        min_rows=5,
        advantages=["Captures a simple long-run trend with zero tuning"],
        limitations=["Assumes the trend continues unchanged forever"],
        good_for=["trending baseline"],
        hyperparameters=[],
        metrics=METRICS,
        tags=["baseline"],
    ),
    spec(
        key="moving_average_forecast",
        name="Moving Average",
        category="time_series",
        family="smoothing",
        task_types=TS,
        builder=lazy("dsai.registry.ts_adapters:MovingAverageForecaster"),
        module="pandas",
        interpretability=TRANSPARENT,
        cost=Cost.VERY_LOW,
        min_rows=10,
        advantages=["Smooths out noise", "Everyone in the business understands it"],
        limitations=["Flat forecast — cannot follow a trend", "Lags turning points"],
        good_for=["stable series", "noise reduction"],
        hyperparameters=[hp("window", "int", 3, 2, 24, description="How many recent periods to average.")],
        metrics=METRICS,
    ),
    spec(
        key="simple_exponential_smoothing",
        name="Simple Exponential Smoothing",
        category="time_series",
        family="smoothing",
        task_types=TS,
        builder=lazy("dsai.registry.ts_adapters:SimpleExponentialSmoothingForecaster"),
        module="statsmodels",
        interpretability=TRANSPARENT,
        cost=Cost.LOW,
        min_rows=10,
        assumptions=["No systematic trend or seasonality"],
        advantages=["Weights recent observations more heavily", "One parameter, fitted automatically"],
        limitations=["Flat forecasts", "Ignores seasonality"],
        good_for=["level-only series"],
        hyperparameters=[],
        metrics=METRICS,
    ),
    spec(
        key="holt_linear",
        name="Holt's Linear Trend",
        category="time_series",
        family="smoothing",
        task_types=TS,
        builder=lazy("dsai.registry.ts_adapters:ExponentialSmoothingForecaster"),
        module="statsmodels",
        interpretability=TRANSPARENT,
        cost=Cost.LOW,
        min_rows=15,
        assumptions=["A trend exists but no seasonality"],
        advantages=["Follows trends while staying simple and fast"],
        limitations=["Undamped trends can run away over long horizons"],
        good_for=["trending non-seasonal series"],
        hyperparameters=[
            hp("trend", "categorical", "add", choices=["add", "mul"]),
            hp("damped_trend", "bool", False, description="Damping flattens the trend as the horizon grows — safer for long forecasts."),
        ],
        metrics=METRICS,
    ),
    spec(
        key="holt_winters",
        name="Holt-Winters (triple exponential smoothing)",
        category="time_series",
        family="smoothing",
        task_types=TS,
        builder=lazy("dsai.registry.ts_adapters:ExponentialSmoothingForecaster"),
        module="statsmodels",
        interpretability=MODERATE,
        cost=Cost.LOW,
        min_rows=24,
        assumptions=["Trend and a stable, repeating seasonal pattern", "At least two full seasons of history"],
        advantages=["Handles level, trend and seasonality together", "Reliable workhorse for business forecasting"],
        limitations=["Needs two full seasonal cycles", "Struggles when seasonality shifts over time"],
        good_for=["seasonal business series", "monthly or quarterly demand"],
        hyperparameters=[
            hp("trend", "categorical", "add", choices=["add", "mul", None]),
            hp("seasonal", "categorical", "add", choices=["add", "mul", None],
               description="Use multiplicative when seasonal swings grow with the level."),
            hp("seasonal_periods", "int", 12, 2, 52, description="Observations per season (12 monthly, 4 quarterly, 7 daily-weekly)."),
            hp("damped_trend", "bool", False),
        ],
        metrics=METRICS,
        tags=["seasonal", "workhorse"],
    ),
    spec(
        key="arima",
        name="ARIMA",
        category="time_series",
        family="statistical",
        task_types=TS,
        builder=lazy("dsai.registry.ts_adapters:ARIMAForecaster"),
        module="statsmodels",
        interpretability=MODERATE,
        cost=Cost.MEDIUM,
        min_rows=30,
        assumptions=["Series is stationary after differencing", "Residuals are white noise"],
        advantages=["Well-founded theory", "Genuine prediction intervals", "Handles autocorrelation explicitly"],
        limitations=["Order selection needs care", "Assumes a linear structure", "No seasonality unless you use SARIMA"],
        good_for=["non-seasonal series with autocorrelation"],
        hyperparameters=[
            hp("order", "categorical", (1, 1, 1), choices=[(1, 0, 0), (0, 1, 1), (1, 1, 1), (2, 1, 2)],
               description="(p, d, q): AR terms, differences, MA terms."),
            hp("auto", "bool", False, description="Search orders by AIC instead of using the fixed order."),
        ],
        metrics=METRICS,
        tags=["intervals"],
    ),
    spec(
        key="auto_arima",
        name="Auto-ARIMA (AIC order search)",
        category="time_series",
        family="statistical",
        task_types=TS,
        builder=lazy("dsai.registry.ts_adapters:ARIMAForecaster"),
        module="statsmodels",
        interpretability=MODERATE,
        cost=Cost.HIGH,
        min_rows=40,
        assumptions=["Same as ARIMA; differencing order chosen by an ADF test"],
        advantages=["Removes the guesswork from order selection"],
        limitations=["Slow — it fits many candidate models", "AIC can overfit short series"],
        good_for=["hands-off forecasting"],
        hyperparameters=[hp("auto", "fixed", True, tune=False),
                         hp("seasonal_order", "categorical", (0, 0, 0, 0), choices=[(0, 0, 0, 0), (0, 0, 0, 12)])],
        metrics=METRICS,
    ),
    spec(
        key="sarima",
        name="SARIMA (seasonal ARIMA)",
        category="time_series",
        family="statistical",
        task_types=TS,
        builder=lazy("dsai.registry.ts_adapters:SARIMAXForecaster"),
        module="statsmodels",
        interpretability=MODERATE,
        cost=Cost.HIGH,
        min_rows=48,
        assumptions=["Seasonal and non-seasonal structure both present", "Stationary after differencing"],
        advantages=["Models seasonality inside the ARIMA framework", "Prediction intervals included"],
        limitations=["Many orders to choose", "Slow to fit", "Needs several seasonal cycles"],
        good_for=["seasonal series with autocorrelation"],
        hyperparameters=[
            hp("order", "categorical", (1, 1, 1), choices=[(1, 1, 1), (0, 1, 1), (2, 1, 2)]),
            hp("seasonal_order", "categorical", (1, 0, 1, 12), choices=[(1, 0, 1, 12), (0, 1, 1, 12), (1, 1, 1, 4)]),
        ],
        metrics=METRICS,
        tags=["seasonal", "intervals"],
    ),
    spec(
        key="theta",
        name="Theta Method",
        category="time_series",
        family="statistical",
        task_types=TS,
        builder=lazy("dsai.registry.ts_adapters:ThetaForecaster"),
        module="statsmodels",
        interpretability=MODERATE,
        cost=Cost.LOW,
        min_rows=15,
        assumptions=["Series decomposes into a long-run trend and short-run variation"],
        advantages=["Won the M3 competition", "Extremely strong for how simple it is", "Fast"],
        limitations=["Little to interpret beyond the forecast itself"],
        good_for=["general business forecasting", "benchmark to beat"],
        hyperparameters=[hp("period", "int", 12, 2, 52), hp("deseasonalize", "bool", True)],
        metrics=METRICS,
        tags=["strong_benchmark"],
    ),
    spec(
        key="unobserved_components",
        name="State-Space Structural Model",
        category="time_series",
        family="statistical",
        task_types=TS,
        builder=lazy("dsai.registry.ts_adapters:UnobservedComponentsForecaster"),
        module="statsmodels",
        interpretability=MODERATE,
        cost=Cost.HIGH,
        min_rows=30,
        assumptions=["Series is a sum of unobserved level, trend, seasonal and noise components"],
        advantages=["Decomposes the series into readable components", "Handles missing periods natively", "Prediction intervals"],
        limitations=["Slow to fit", "Component specification takes judgement"],
        good_for=["decomposition", "series with gaps", "structural interpretation"],
        hyperparameters=[
            hp("level", "categorical", "local linear trend",
               choices=["local level", "local linear trend", "smooth trend"]),
            hp("seasonal", "int", None, 2, 52),
        ],
        metrics=METRICS,
        tags=["decomposition", "intervals"],
    ),
    spec(
        key="var",
        name="Vector Autoregression (VAR)",
        category="time_series",
        family="statistical",
        task_types=TS,
        builder=lazy("dsai.registry.ts_adapters:VARForecaster"),
        module="statsmodels",
        interpretability=MODERATE,
        cost=Cost.MEDIUM,
        min_rows=50,
        assumptions=["Several stationary series that influence each other", "Enough history for lags × series parameters"],
        advantages=["Captures feedback between series", "Supports Granger-causality testing"],
        limitations=["Parameter count explodes with series and lags", "Requires stationarity"],
        good_for=["interdependent series", "macro-style data"],
        hyperparameters=[hp("maxlags", "int", 5, 1, 24)],
        metrics=METRICS,
        tags=["multivariate"],
    ),
    spec(
        key="ml_forecast_random_forest",
        name="Random Forest Forecaster (lag features)",
        category="time_series",
        family="ensemble",
        task_types=TS,
        builder=lazy("dsai.registry.ts_adapters:MLForecaster"),
        module="sklearn",
        interpretability=MODERATE,
        cost=Cost.MEDIUM,
        nonlinear=True,
        min_rows=50,
        assumptions=["Future values depend nonlinearly on recent lags"],
        advantages=["Captures nonlinear dynamics", "Lag importances show what drives the forecast"],
        limitations=[
            "Cannot extrapolate beyond values seen in training — a hard limit for trending series",
            "Errors compound over a long horizon because forecasts feed back as inputs",
        ],
        good_for=["nonlinear, non-trending series", "series with many lags of influence"],
        hyperparameters=[
            hp("n_lags", "int", 12, 2, 52, description="How many past periods the model may look at."),
            hp("seasonal_period", "int", None, 2, 52),
        ],
        metrics=METRICS,
        tags=["ml_forecasting"],
    ),
    spec(
        key="ml_forecast_gradient_boosting",
        name="Gradient Boosting Forecaster (lag features)",
        category="time_series",
        family="ensemble",
        task_types=TS,
        builder=lazy("dsai.registry.ts_adapters:make_ml_forecaster"),
        module="sklearn",
        interpretability=MODERATE,
        cost=Cost.HIGH,
        nonlinear=True,
        min_rows=60,
        advantages=["Usually the strongest ML forecaster on tabular lag features"],
        limitations=["Same extrapolation limit as any tree model", "Needs enough history to build lags"],
        good_for=["complex nonlinear series with adequate history"],
        hyperparameters=[
            hp("estimator_path", "fixed", "sklearn.ensemble:GradientBoostingRegressor", tune=False),
            hp("n_lags", "int", 12, 2, 52),
            hp("seasonal_period", "int", None, 2, 52),
        ],
        metrics=METRICS,
        tags=["ml_forecasting"],
    ),
    spec(
        key="ml_forecast_ridge",
        name="Ridge Forecaster (lag features)",
        category="time_series",
        family="linear",
        task_types=TS,
        builder=lazy("dsai.registry.ts_adapters:make_ml_forecaster"),
        module="sklearn",
        interpretability=MODERATE,
        cost=Cost.LOW,
        min_rows=30,
        advantages=["Linear in the lags, so it *can* extrapolate a trend", "Fast and stable"],
        limitations=["Misses nonlinear dynamics"],
        good_for=["trending series where tree forecasters fail"],
        hyperparameters=[
            hp("estimator_path", "fixed", "sklearn.linear_model:Ridge", tune=False),
            hp("n_lags", "int", 12, 2, 52),
            hp("seasonal_period", "int", None, 2, 52),
        ],
        metrics=METRICS,
        tags=["ml_forecasting"],
    ),
    spec(
        key="ml_forecast_lightgbm",
        name="LightGBM Forecaster (lag features)",
        category="time_series",
        family="ensemble",
        task_types=TS,
        builder=lazy("dsai.registry.ts_adapters:make_ml_forecaster"),
        module="lightgbm",
        interpretability=MODERATE,
        cost=Cost.MEDIUM,
        nonlinear=True,
        min_rows=100,
        advantages=["Fast on long histories with many lag features"],
        limitations=["Cannot extrapolate", "Extra dependency"],
        good_for=["long histories", "high-frequency data"],
        hyperparameters=[
            hp("estimator_path", "fixed", "lightgbm:LGBMRegressor", tune=False),
            hp("n_lags", "int", 24, 2, 104),
            hp("seasonal_period", "int", None, 2, 52),
            hp("verbose", "fixed", -1, tune=False),
        ],
        metrics=METRICS,
        tags=["ml_forecasting"],
    ),
    spec(
        key="ml_forecast_mlp",
        name="Neural Forecaster (MLP on lag features)",
        category="time_series",
        family="neural",
        task_types=TS,
        builder=lazy("dsai.registry.ts_adapters:make_ml_forecaster"),
        module="sklearn",
        interpretability=OPAQUE,
        cost=Cost.HIGH,
        nonlinear=True,
        min_rows=150,
        advantages=["Learns smooth nonlinear dynamics given a long history"],
        limitations=["Data hungry", "Unstable on short series", "Nothing to interpret"],
        good_for=["long, complex histories"],
        hyperparameters=[
            hp("estimator_path", "fixed", "sklearn.neural_network:MLPRegressor", tune=False),
            hp("n_lags", "int", 12, 2, 52),
            hp("hidden_layer_sizes", "categorical", (64, 32), choices=[(32,), (64, 32)]),
            hp("max_iter", "fixed", 800, tune=False),
            hp("random_state", "fixed", 42, tune=False),
        ],
        metrics=METRICS,
        tags=["ml_forecasting"],
    ),
]

for _spec in SPECS:
    register(_spec, replace=True)

_LOADED = True
