"""Export an analysis as runnable Python.

The generated script is the honest test of reproducibility: if it does not
reproduce the numbers, the run was not reproducible. It uses plain pandas and
scikit-learn so it can be read, reviewed and modified by someone who has never
seen this platform.
"""

from __future__ import annotations

import datetime as _dt
from typing import Any

from dsai.core.schema import TaskType
from dsai.preprocessing.pipeline import PreprocessingPipeline
from dsai.registry.base import REGISTRY

_HEADER = '''"""
{title}

Generated by the DSAI platform on {timestamp}.
Run manifest fingerprint: {fingerprint}

This script reproduces the analysis end to end using pandas and scikit-learn
directly. Nothing in it depends on the platform, so it can be reviewed,
modified and run anywhere.
"""

import warnings

import numpy as np
import pandas as pd

warnings.filterwarnings("ignore")

RANDOM_STATE = {seed}
np.random.seed(RANDOM_STATE)
'''


def generate_script(run: Any, data_path: str = "your_data.csv") -> str:
    """Produce a standalone script reproducing this run."""
    from dsai.repro.provenance import build_manifest

    manifest = build_manifest(run)
    objective = run.objective
    task = objective.task_type if objective else TaskType.EXPLORATORY

    blocks = [
        _HEADER.format(
            title=f"Analysis of {run.dataset_name}",
            timestamp=_dt.datetime.now().strftime("%Y-%m-%d %H:%M"),
            fingerprint=manifest.fingerprint(),
            seed=run.settings.random_state,
        ),
        _load_block(run, data_path),
    ]

    if task is TaskType.TIME_SERIES_FORECAST:
        blocks.append(_forecast_block(run))
    elif task is TaskType.CLUSTERING:
        blocks.append(_preprocessing_block(run.pipeline, needs_target=False))
        blocks.append(_clustering_block(run))
    elif task.is_supervised:
        blocks.append(_preprocessing_block(run.pipeline, needs_target=True))
        blocks.append(_supervised_block(run))
    elif task is TaskType.ANOMALY_DETECTION:
        blocks.append(_preprocessing_block(run.pipeline, needs_target=False))
        blocks.append(_anomaly_block(run))
    else:
        blocks.append(_exploratory_block(run))

    blocks.append(_footer(run, manifest))
    return "\n\n".join(b for b in blocks if b)


# --------------------------------------------------------------------------
# blocks
# --------------------------------------------------------------------------

def _load_block(run: Any, data_path: str) -> str:
    source = run.source
    if source is not None and source.kind == "sql":
        loader = (
            "from sqlalchemy import create_engine, text\n\n"
            f"CONNECTION = {source.connection!r}  # add credentials before running\n"
            f"QUERY = {source.query!r}\n"
            "with create_engine(CONNECTION).connect() as connection:\n"
            "    df = pd.read_sql(text(QUERY), connection)"
        )
    else:
        path = (source.path if source and source.path else data_path) or data_path
        reader = {
            "excel": "pd.read_excel", "parquet": "pd.read_parquet",
            "json": "pd.read_json", "feather": "pd.read_feather",
        }.get(source.file_format if source else "csv", "pd.read_csv")
        loader = f"DATA_PATH = {str(path)!r}\ndf = {reader}(DATA_PATH)"

    lines = [
        "# " + "-" * 74,
        "# 1. Load the data",
        "# " + "-" * 74,
        loader,
        'print(f"Loaded {len(df):,} rows x {df.shape[1]} columns")',
    ]

    if run.profile:
        datetime_columns = run.profile.datetime_columns
        if datetime_columns:
            lines += [
                "",
                "# Columns the profiler identified as dates",
                f"for column in {datetime_columns!r}:",
                "    df[column] = pd.to_datetime(df[column], errors='coerce')",
            ]
    return "\n".join(lines)


def _preprocessing_block(pipeline: PreprocessingPipeline | None, needs_target: bool) -> str:
    if pipeline is None:
        return ""
    lines = [
        "# " + "-" * 74,
        "# 2. Preprocessing",
        "#",
        "# Row operations run before the split (they change which rows exist).",
        "# Column transformations go INSIDE the pipeline so they are fitted on",
        "# training folds only — this is what prevents leakage.",
        "# " + "-" * 74,
    ]
    for step in pipeline.row_steps:
        lines.append(f"# {step.spec.name}")
        if step.step_key == "drop_duplicates":
            subset = step.columns
            lines.append(f"df = df.drop_duplicates({f'subset={subset!r}' if subset else ''})")
        elif step.step_key == "drop_rows_missing":
            lines.append(f"df = df.dropna(subset={step.columns!r})" if step.columns else "df = df.dropna()")
        elif step.step_key == "impute_forward_fill":
            lines.append(f"df[{step.columns!r}] = df[{step.columns!r}].ffill().bfill()")
        elif step.step_key == "remove_outlier_rows":
            factor = step.params.get("factor", 3.0)
            lines += [
                f"_cols = {step.columns!r}",
                "_q1, _q3 = df[_cols].quantile(0.25), df[_cols].quantile(0.75)",
                f"_iqr = (_q3 - _q1).replace(0, np.nan)",
                f"_mask = ~(((df[_cols] < _q1 - {factor} * _iqr) | (df[_cols] > _q3 + {factor} * _iqr)).any(axis=1))",
                "df = df[_mask.fillna(True)]",
            ]

    column_steps = pipeline.column_steps
    if not column_steps:
        lines.append("preprocessor = None")
        return "\n".join(lines)

    imports, stages, inline = _pipeline_stages(column_steps)
    lines += ["", *sorted(imports), "from sklearn.pipeline import Pipeline",
              "from sklearn.base import BaseEstimator, TransformerMixin", ""]
    lines += ["", _inline_transformer_source(inline), ""]
    lines.append("preprocessor = Pipeline([")
    lines += [f"    {stage}," for stage in stages]
    lines.append("])")
    return "\n".join(lines)


def _inline_transformer_source(names: set[str]) -> str:
    """Copy the source of the custom transformers into the exported script.

    Importing them from this package would make the script depend on the very
    platform it is meant to replace, so the source travels with it instead.
    """
    import inspect

    from dsai.preprocessing import transformers as T

    ordered = ["_as_frame"] + sorted(n for n in names if n != "_as_frame")
    blocks = [
        "# " + "-" * 74,
        "# Transformers copied from the platform so this script stands alone.",
        "# " + "-" * 74,
        "from typing import Any",
    ]
    for name in ordered:
        member = getattr(T, name, None)
        if member is None:
            continue
        try:
            blocks.append(inspect.getsource(member).rstrip())
        except (OSError, TypeError):
            continue
    return "\n\n\n".join(blocks)


def _pipeline_stages(column_steps) -> tuple[set[str], list[str], set[str]]:
    """Translate pipeline steps into readable sklearn constructor calls."""
    # Custom transformers are inlined as source rather than imported, so the
    # exported script runs anywhere pandas and scikit-learn are installed.
    imports: set[str] = set()
    needed_inline: set[str] = {"FrameTransformer", "NumericCoercer"}
    stages: list[str] = []
    mapping = {
        "impute_mean": ("from sklearn.impute import SimpleImputer", "SimpleImputer(strategy='mean')"),
        "impute_median": ("from sklearn.impute import SimpleImputer", "SimpleImputer(strategy='median')"),
        "impute_mode": ("from sklearn.impute import SimpleImputer", "SimpleImputer(strategy='most_frequent')"),
        "impute_knn": ("from sklearn.impute import KNNImputer", "KNNImputer(n_neighbors={n_neighbors})"),
        "standard_scale": ("from sklearn.preprocessing import StandardScaler", "StandardScaler()"),
        "minmax_scale": ("from sklearn.preprocessing import MinMaxScaler", "MinMaxScaler()"),
        "robust_scale": ("from sklearn.preprocessing import RobustScaler", "RobustScaler()"),
        "maxabs_scale": ("from sklearn.preprocessing import MaxAbsScaler", "MaxAbsScaler()"),
        "one_hot_encode": ("from sklearn.preprocessing import OneHotEncoder",
                           "OneHotEncoder(sparse_output=False, handle_unknown='infrequent_if_exist')"),
        "ordinal_encode": ("from sklearn.preprocessing import OrdinalEncoder",
                           "OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1)"),
        "yeo_johnson": ("from sklearn.preprocessing import PowerTransformer",
                        "PowerTransformer(method='yeo-johnson', standardize=False)"),
        "box_cox": ("from sklearn.preprocessing import PowerTransformer",
                    "PowerTransformer(method='box-cox', standardize=False)"),
        "polynomial_features": ("from sklearn.preprocessing import PolynomialFeatures",
                                "PolynomialFeatures(degree={degree}, include_bias=False)"),
        "pca_reduce": ("@NamedPCA", "NamedPCA(n_components={n_components})"),
        "log_transform": ("@LogTransformer", "LogTransformer()"),
        "target_encode": ("@TargetEncoder", "TargetEncoder(smoothing={smoothing})"),
        "frequency_encode": ("@FrequencyEncoder", "FrequencyEncoder()"),
        "datetime_features": ("@DateTimeFeatures", "DateTimeFeatures()"),
        "text_features": ("@TextFeatures", "TextFeatures()"),
        "group_rare_categories": ("@RareCategoryGrouper", "RareCategoryGrouper(min_frequency={min_frequency})"),
        "winsorize": ("@WinsorizeTransformer", "WinsorizeTransformer({lower_quantile}, {upper_quantile})"),
        "clip_iqr": ("@OutlierClipTransformer", "OutlierClipTransformer({factor})"),
    }

    for i, step in enumerate(column_steps):
        name = f"{i:02d}_{step.step_key}"
        columns = step.columns
        if step.step_key == "drop_columns":
            needed_inline.add("ColumnSelector")
            stages.append(f"('{name}', ColumnSelector(columns={columns!r}, mode='drop'))")
            continue
        entry = mapping.get(step.step_key)
        if entry is None:
            stages.append(f"# ('{name}', ...)  # {step.spec.name} — add manually if needed")
            continue
        import_line, template = entry
        if import_line.startswith("@"):
            needed_inline.add(import_line[1:])
        else:
            imports.add(import_line)
        params = {**step.spec.default_params(), **step.params}
        try:
            inner = template.format(**params)
        except (KeyError, IndexError):
            inner = template.split("(")[0] + "()"
        stages.append(f"('{name}', FrameTransformer({inner}, columns={columns!r}))")

    stages.append("('coerce', NumericCoercer())")
    return imports, stages, needed_inline


def _supervised_block(run: Any) -> str:
    best = run.best
    objective = run.objective
    if best is None:
        return "# No model was selected — nothing to reproduce."

    spec = REGISTRY.get(best.model_key) if best.model_key in REGISTRY else None
    import_path = getattr(spec.builder, "import_path", "") if spec and spec.builder else ""
    module, _, class_name = import_path.partition(":")
    params = {k: v for k, v in (best.hyperparameters or {}).items() if v is not None}

    validation = run.plan.validation_strategy if run.plan else {}
    splitter = {
        "stratified_kfold": "StratifiedKFold",
        "repeated_kfold": "RepeatedKFold",
        "repeated_stratified_kfold": "RepeatedStratifiedKFold",
        "time_series_split": "TimeSeriesSplit",
    }.get(validation.get("strategy", "kfold"), "KFold")
    n_splits = validation.get("n_splits", 5)
    metric = run.plan.primary_metric if run.plan else "r2"

    scoring = {
        "rmse": "neg_root_mean_squared_error", "mae": "neg_mean_absolute_error",
        "r2": "r2", "roc_auc": "roc_auc", "pr_auc": "average_precision",
        "f1": "f1", "f1_macro": "f1_macro", "balanced_accuracy": "balanced_accuracy",
        "accuracy": "accuracy",
    }.get(metric, "r2")

    splitter_args = "n_splits=N_SPLITS" + ("" if splitter == "TimeSeriesSplit" else ", shuffle=True, random_state=RANDOM_STATE")
    scorer_import = "from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score" \
        if objective.task_type is TaskType.REGRESSION else \
        "from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score"

    lines = [
        "# " + "-" * 74,
        f"# 3. Model: {best.model_name}",
        "# " + "-" * 74,
        f"from {module} import {class_name}" if module else f"# import {best.model_key} manually",
        f"from sklearn.model_selection import {splitter}, cross_val_score, train_test_split",
        "from sklearn.pipeline import Pipeline",
        scorer_import,
        "",
        f"TARGET = {objective.target!r}",
        f"FEATURES = {best.features!r}",
        f"N_SPLITS = {n_splits}",
        "",
        "data = df.dropna(subset=[TARGET])",
        "X = data[FEATURES]",
        "y = data[TARGET]",
        "",
        f"model = {class_name}({_format_params(params)})" if module else "model = ...  # build the estimator",
        "pipeline = Pipeline(list(preprocessor.steps) + [('model', model)]) if preprocessor else Pipeline([('model', model)])",
        "",
        "# Cross-validation. Every fitted transformation is refitted on each",
        "# training fold, so nothing from the held-out rows reaches the model.",
        f"cv = {splitter}({splitter_args})",
        f"SCORING = {scoring!r}",
        "scores = cross_val_score(pipeline, X, y, cv=cv, scoring=SCORING)",
        'print(f"Cross-validated {SCORING}: {scores.mean():.4f} (+/- {scores.std():.4f})")',
        "",
        "# Hold-out evaluation",
    ]
    stratify = ", stratify=y" if objective.task_type.is_classification else ""
    lines += [
        f"X_train, X_test, y_train, y_test = train_test_split(",
        f"    X, y, test_size={run.settings.test_size}, random_state=RANDOM_STATE{stratify}",
        ")",
        "pipeline.fit(X_train, y_train)",
        "predictions = pipeline.predict(X_test)",
    ]
    if objective.task_type is TaskType.REGRESSION:
        lines += [
            'print(f"R2:   {r2_score(y_test, predictions):.4f}")',
            'print(f"RMSE: {np.sqrt(mean_squared_error(y_test, predictions)):,.2f}")',
            'print(f"MAE:  {mean_absolute_error(y_test, predictions):,.2f}")',
        ]
    else:
        lines += [
            "print(classification_report(y_test, predictions))",
            "print(confusion_matrix(y_test, predictions))",
        ]
    lines += [
        "",
        "# Feature importance (permutation — works for any model)",
        "from sklearn.inspection import permutation_importance",
        "",
        "importance = permutation_importance(pipeline, X_test, y_test, n_repeats=10, random_state=RANDOM_STATE, scoring=SCORING)",
        "ranking = pd.DataFrame({'feature': FEATURES, 'importance': importance.importances_mean})",
        "print(ranking.sort_values('importance', ascending=False).head(15).to_string(index=False))",
    ]
    return "\n".join(lines)


def _clustering_block(run: Any) -> str:
    best = run.best
    if best is None:
        return ""
    spec = REGISTRY.get(best.model_key) if best.model_key in REGISTRY else None
    import_path = getattr(spec.builder, "import_path", "") if spec and spec.builder else ""
    module, _, class_name = import_path.partition(":")
    params = {k: v for k, v in (best.hyperparameters or {}).items() if v is not None}
    return "\n".join([
        "# " + "-" * 74,
        f"# 3. Clustering: {best.model_name}",
        "# " + "-" * 74,
        f"from {module} import {class_name}" if module else "# import the clusterer",
        "from sklearn.metrics import calinski_harabasz_score, davies_bouldin_score, silhouette_score",
        "",
        f"FEATURES = {best.features!r}",
        "X = df[FEATURES]",
        "X_prepared = preprocessor.fit_transform(X) if preprocessor else X.to_numpy()",
        "",
        f"clusterer = {class_name}({_format_params(params)})",
        "labels = clusterer.fit_predict(X_prepared)",
        "df['cluster'] = labels",
        "",
        'print(f"Clusters found: {len(set(labels) - {-1})}")',
        'print(f"Silhouette:     {silhouette_score(X_prepared, labels):.4f}")',
        'print(f"Calinski-H:     {calinski_harabasz_score(X_prepared, labels):,.1f}")',
        'print(f"Davies-Bouldin: {davies_bouldin_score(X_prepared, labels):.4f}")',
        "",
        "# Segment profile in the original units",
        "print(df.groupby('cluster')[[c for c in FEATURES if pd.api.types.is_numeric_dtype(df[c])]].mean().round(2))",
        "print(df['cluster'].value_counts().sort_index())",
    ])


def _anomaly_block(run: Any) -> str:
    best = run.best
    if best is None:
        return ""
    spec = REGISTRY.get(best.model_key) if best.model_key in REGISTRY else None
    import_path = getattr(spec.builder, "import_path", "") if spec and spec.builder else ""
    module, _, class_name = import_path.partition(":")
    params = {k: v for k, v in (best.hyperparameters or {}).items() if v is not None}
    return "\n".join([
        "# " + "-" * 74,
        f"# 3. Anomaly detection: {best.model_name}",
        "# " + "-" * 74,
        f"from {module} import {class_name}" if module else "# import the detector",
        "",
        f"FEATURES = {best.features!r}",
        "X = df[FEATURES]",
        "X_prepared = preprocessor.fit_transform(X) if preprocessor else X.to_numpy()",
        "",
        f"detector = {class_name}({_format_params(params)})",
        "flags = detector.fit_predict(X_prepared)",
        "df['is_anomaly'] = flags == -1",
        'print(f"Flagged {df.is_anomaly.sum():,} of {len(df):,} rows ({df.is_anomaly.mean():.1%})")',
        "print(df[df.is_anomaly].head(20).to_string())",
    ])


def _forecast_block(run: Any) -> str:
    best = run.best
    objective = run.objective
    if best is None:
        return ""
    seasonal = best.extras.get("seasonal_period")
    horizon = best.extras.get("horizon", 12)
    return "\n".join([
        "# " + "-" * 74,
        f"# 3. Forecasting: {best.model_name}",
        "# " + "-" * 74,
        f"from dsai.registry.ts_adapters import {_forecaster_class(best.model_key)}",
        "",
        f"TIME_COLUMN = {objective.time_column!r}",
        f"TARGET = {objective.target!r}",
        f"HORIZON = {horizon}",
        f"SEASONAL_PERIOD = {seasonal!r}",
        "",
        "series = (df[[TIME_COLUMN, TARGET]].dropna()",
        "          .assign(**{TIME_COLUMN: lambda d: pd.to_datetime(d[TIME_COLUMN])})",
        "          .sort_values(TIME_COLUMN).set_index(TIME_COLUMN)[TARGET].astype(float))",
        "if series.index.has_duplicates:",
        "    series = series.groupby(level=0).mean()",
        "",
        "# Hold out the last HORIZON periods to check accuracy honestly",
        "train, test = series.iloc[:-HORIZON], series.iloc[-HORIZON:]",
        f"model = {_forecaster_class(best.model_key)}({_format_params(best.hyperparameters or {})})",
        "model.fit(train)",
        "predictions = model.predict(len(test))",
        "",
        "mae = np.mean(np.abs(test.to_numpy() - predictions))",
        "naive = np.mean(np.abs(train.to_numpy()[1:] - train.to_numpy()[:-1]))",
        'print(f"MAE:  {mae:,.2f}")',
        'print(f"MASE: {mae / naive:.3f}  (below 1.0 beats a naive last-value forecast)")',
        "",
        "# Refit on everything and forecast forward",
        f"final = {_forecaster_class(best.model_key)}({_format_params(best.hyperparameters or {})})",
        "final.fit(series)",
        "forecast = final.predict(HORIZON)",
        "print(pd.Series(forecast, name='forecast').round(2).to_string())",
    ])


def _forecaster_class(model_key: str) -> str:
    spec = REGISTRY.get(model_key) if model_key in REGISTRY else None
    path = getattr(spec.builder, "import_path", "") if spec and spec.builder else ""
    return path.partition(":")[2] or "NaiveForecaster"


def _exploratory_block(run: Any) -> str:
    return "\n".join([
        "# " + "-" * 74,
        "# 3. Exploratory analysis",
        "# " + "-" * 74,
        "print(df.describe(include='all').T.to_string())",
        "print(df.isna().sum().sort_values(ascending=False).head(20).to_string())",
        "numeric = df.select_dtypes(include='number')",
        "print(numeric.corr().round(3).to_string())",
    ])


def _footer(run: Any, manifest: Any) -> str:
    lines = [
        "# " + "-" * 74,
        "# Reproducibility notes",
        "# " + "-" * 74,
        f"# Random seed:  {run.settings.random_state}",
        f"# Fingerprint:  {manifest.fingerprint()}",
        "# Environment at the time of the original run:",
    ]
    lines += [f"#   {k}: {v}" for k, v in (run.environment or {}).items()]
    if run.warnings:
        lines += ["#", "# Warnings raised during the original analysis:"]
        lines += [f"#   - {w}" for w in run.warnings[:10]]
    return "\n".join(lines)


def _format_params(params: dict[str, Any]) -> str:
    if not params:
        return ""
    return ", ".join(f"{k}={v!r}" for k, v in params.items())
